/**
 * UI strings of the report file and the e-mail. Both languages ship inside every report so the reader can switch;
 * `zh` is typed against `en`, so a missing key fails compilation instead of showing a raw key.
 */
import type { Lang } from '@resonance/schema'

const en = {
  daily: 'Daily edition',
  weekly: 'Weekly recap',
  range: 'Report',
  window: 'Edition window',
  yourTime: 'Your time',
  generated: 'Generated',
  preliminary: 'Preliminary: this edition has not settled yet, so late engagement can still change the ranking.',
  brief: 'The brief',
  briefWeek: 'The week in brief',
  resonance: 'Resonance',
  resonanceSub: 'Things echoing across several boards',
  boards: 'Boards',
  categories: 'Categories',
  all: 'All',
  allCats: 'Everything',
  filter: 'Filter items',
  filterPh: 'Filter by word…',
  noMatch: 'Nothing matches these filters.',
  clear: 'Clear filters',
  empty: 'Nothing on this board.',
  details: 'Details',
  points: 'Key points',
  why: 'Why it matters',
  breakdown: 'Score breakdown',
  signal: 'Signal',
  raw: 'Raw',
  norm: 'Norm',
  pts: 'Points',
  total: 'Total',
  score: 'heat score',
  weekHeat: 'weekly heat',
  lastScore: 'Latest daily score',
  links: 'Echoes on other boards',
  mySummary: 'My summary',
  new: 'NEW',
  back: 'BACK',
  daysOn: '{n} days on board',
  streak: '{n}-day streak',
  boardsN: 'spans {n} boards',
  today: 'today',
  upvotes: 'upvotes',
  code: 'code',
  etAl: 'et al.',
  byPosition: 'ranked by list position',
  discuss: 'HN thread',
  comments: 'comments',
  theme: 'Colour theme',
  auto: 'Auto',
  light: 'Light',
  dark: 'Dark',
  lang: 'Language',
  site: 'Open the site',
  repo: 'Source code',
  openReport: 'Open the interactive report',
  attached: 'The full interactive report is attached as an HTML file.',
  footMail: "Sent by your own AI Resonance workflow. Change the schedule in the site's Settings › Delivery.",
  test: '[Test]',
  week: 'Week',
  v_dig: 'Dig in',
  v_bookmark: 'Bookmark',
  v_skip: 'Skip',
  c_release: 'Release',
  c_product: 'Product',
  c_research: 'Research',
  c_tool: 'Tool',
  c_engineering: 'Engineering',
  c_discussion: 'Discussion',
  c_industry: 'Industry',
  c_policy: 'Policy',
  k_model: 'Model',
  k_product: 'Product',
  k_research: 'Research',
  k_engineering: 'Engineering',
  k_company: 'Company',
  p_x: 'X',
  p_reddit: 'Reddit',
  b_repos: 'Repos',
  b_hf: 'HF Trending',
  b_news: 'Hacker News',
  b_social: 'Social',
  b_labs: 'Labs',
  m_starsToday: 'stars today',
  m_upvotes: 'upvotes',
  m_points: 'points',
  m_likes: 'likes',
  m_score: 'score',
}

/** Every UI string id. */
export type StringKey = keyof typeof en

const zh: Record<StringKey, string> = {
  daily: '日报',
  weekly: '周报',
  range: '报告',
  window: '收录时段',
  yourTime: '你的时间',
  generated: '生成于',
  preliminary: '初步版本：本期尚未定稿，后续的互动数据仍可能改变排名。',
  brief: '今日要点',
  briefWeek: '本周要点',
  resonance: '共振',
  resonanceSub: '在多个榜单间相互呼应的内容',
  boards: '榜单',
  categories: '分类',
  all: '全部',
  allCats: '全部分类',
  filter: '筛选条目',
  filterPh: '输入关键词筛选…',
  noMatch: '没有符合筛选条件的条目。',
  clear: '清除筛选',
  empty: '这个榜单暂无条目。',
  details: '详情',
  points: '要点',
  why: '为何重要',
  breakdown: '得分明细',
  signal: '信号',
  raw: '原始值',
  norm: '归一',
  pts: '得分',
  total: '总分',
  score: '热度分',
  weekHeat: '周热度',
  lastScore: '最近一次日榜得分',
  links: '其他榜单上的呼应',
  mySummary: '我的摘要',
  new: '新',
  back: '回归',
  daysOn: '上榜 {n} 天',
  streak: '连续 {n} 天',
  boardsN: '跨 {n} 个榜单',
  today: '今日',
  upvotes: '赞同',
  code: '代码',
  etAl: '等',
  byPosition: '按列表位置排序',
  discuss: 'HN 讨论',
  comments: '评论',
  theme: '配色主题',
  auto: '自动',
  light: '浅色',
  dark: '深色',
  lang: '语言',
  site: '打开网站',
  repo: '源代码',
  openReport: '打开交互式报告',
  attached: '完整的交互式报告已作为 HTML 附件附上。',
  footMail: '由你自己的 AI Resonance 工作流发送。可在网站的「设置 › 投递」中修改发送时间。',
  test: '[测试]',
  week: '周',
  v_dig: '值得深入',
  v_bookmark: '收藏',
  v_skip: '跳过',
  c_release: '发布',
  c_product: '产品',
  c_research: '研究',
  c_tool: '工具',
  c_engineering: '工程',
  c_discussion: '讨论',
  c_industry: '行业',
  c_policy: '政策',
  k_model: '模型',
  k_product: '产品',
  k_research: '研究',
  k_engineering: '工程',
  k_company: '公司',
  p_x: 'X',
  p_reddit: 'Reddit',
  b_repos: '项目',
  b_hf: 'HF 趋势',
  b_news: 'Hacker News',
  b_social: '社区',
  b_labs: '官方动态',
  m_starsToday: '今日星标',
  m_upvotes: '赞同',
  m_points: '分',
  m_likes: '点赞',
  m_score: '得分',
}

/** UI strings per language. */
export const STRINGS: Record<Lang, Record<StringKey, string>> = { en, zh }

/** Fill `{n}` placeholders. */
export function fill(template: string, n: number | string): string {
  return template.replace(/\{n\}/g, String(n))
}
