import type { BeginnerSeed, BeginnerType } from '@resonance/schema'

/** Editorial scores describe the particular resource, never a type-wide bonus.
 * Order: transferable foundations, accessible explanations, practical use, direct authorship.
 * Each dimension is 0–5; these are judgments, not measured learning outcomes.
 * reviewedAt is a review date, never a source publication date.
 */
type Entry = [
  id: string,
  url: string,
  en: string,
  zh: string,
  summaryZh: string,
  summaryEn: string,
  whyZh: string,
  whyEn: string,
  topics: string,
  scores: [number, number, number, number],
  intermediate?: boolean,
]
export function makeBeginnerGroup(type: BeginnerType, entries: Entry[]): BeginnerSeed[] {
  return entries.map(([id, url, en, zh, summaryZh, summaryEn, whyZh, whyEn, topics, scores, intermediate]) => ({
    id,
    type,
    url,
    title: { zh, en },
    summary: { zh: summaryZh, en: summaryEn },
    why: { zh: whyZh, en: whyEn },
    topics: topics.split(','),
    level: intermediate ? 'intermediate' : 'starter',
    scores: { foundation: scores[0], clarity: scores[1], practice: scores[2], authority: scores[3] },
    reviewedAt: '2026-09-21',
    sourceName: new URL(url).hostname.replace(/^www\./, ''),
  }))
}

/** Initial 30 residents: usable tools and workflows, with a small conceptual foundation. */
export const beginnerCatalog: BeginnerSeed[] = [
  ...makeBeginnerGroup('course', [
    [
      'elements-of-ai',
      'https://www.elementsofai.com/',
      'Elements of AI',
      'Elements of AI：非技术读者入门',
      '用概念、实例与练习解释 AI 能做什么和不能做什么。',
      'Concepts, examples and exercises explaining AI capabilities and limitations.',
      '没有编程背景也能先建立判断 AI 产品的基本框架。',
      'Build a framework for evaluating AI products without a coding background.',
      'ai-literacy,foundations',
      [5, 5, 3, 5],
    ],
    [
      'hf-llm-course',
      'https://huggingface.co/learn/llm-course/chapter1/1',
      'Hugging Face LLM Course',
      'Hugging Face 大语言模型课程',
      '从 Transformer、分词与数据集走到模型训练和使用。',
      'Learn transformers, tokenization, datasets and model training.',
      '把模型概念和可运行的 Python 实践连接起来。',
      'Connect model concepts to runnable Python practice.',
      'llm,nlp,python',
      [5, 4, 5, 5],
    ],
    [
      'hf-agents-course',
      'https://huggingface.co/learn/agents-course/unit0/introduction',
      'Hugging Face Agents Course',
      'Hugging Face 智能体课程',
      '学习模型如何调用工具并组织多步任务。',
      'Learn how models call tools and organize multi-step tasks.',
      '适合做过基础聊天应用后理解智能体的边界和实现。',
      'A next step after a basic chat app to understand agent implementation and limits.',
      'agents,tools',
      [4, 4, 5, 5],
      true,
    ],
  ]),
  ...makeBeginnerGroup('book', [
    [
      'hands-on-llm-book',
      'https://github.com/HandsOnLLM/Hands-On-Large-Language-Models',
      'Hands-On Large Language Models',
      '动手学大语言模型',
      '用配套示例理解表示、生成、检索与模型应用。',
      'Companion examples on representations, generation, retrieval and applications.',
      '适合希望同时理解概念与应用模式的读者。',
      'Connect concepts with practical LLM application patterns.',
      'llm,rag',
      [4, 4, 5, 5],
      true,
    ],
  ]),
  ...makeBeginnerGroup('guide', [
    [
      'python-tutorial',
      'https://docs.python.org/3/tutorial/',
      'The Python Tutorial',
      'Python 官方教程',
      '学习语法、数据结构、模块与异常处理。',
      'Learn syntax, data structures, modules and exception handling.',
      '建立阅读和修改 AI 示例代码所需的语言基础。',
      'Build the language skills needed to read and modify AI examples.',
      'python,foundations',
      [3, 4, 5, 5],
    ],
    [
      'transformers-pipeline-guide',
      'https://huggingface.co/docs/transformers/pipeline_tutorial',
      'Transformers Pipelines',
      'Transformers 推理流水线指南',
      '使用现成模型完成常见文本、图像和音频任务。',
      'Use pretrained models for common text, image and audio tasks.',
      '先做出一次本地推理，再深入模型内部。',
      'Complete an inference task before exploring model internals.',
      'llm,inference',
      [4, 4, 5, 5],
    ],
    [
      'gradio-quickstart',
      'https://www.gradio.app/guides/quickstart',
      'Gradio Quickstart',
      'Gradio 交互演示入门',
      '为 Python 函数和模型添加可交互的网页界面。',
      'Add a web interface to Python functions and models.',
      '把实验变成别人能试用的演示。',
      'Turn an experiment into a demo others can try.',
      'apps,python',
      [3, 5, 5, 5],
    ],
    [
      'streamlit-start',
      'https://docs.streamlit.io/get-started',
      'Get Started with Streamlit',
      'Streamlit 数据应用入门',
      '用 Python 构建可交互的数据与 AI 应用。',
      'Build interactive data and AI applications in Python.',
      '适合快速展示数据、模型输出和反馈。',
      'Quickly present data, model outputs and feedback controls.',
      'apps,python',
      [3, 4, 5, 5],
    ],
    [
      'openai-prompt-guide',
      'https://developers.openai.com/api/docs/guides/prompt-engineering',
      'OpenAI Prompt Engineering',
      'OpenAI 提示词设计指南',
      '学习用明确指令、上下文和示例组织模型输入。',
      'Structure model inputs with clear instructions, context and examples.',
      '通过可复现的任务要求改进输出，而非收集万能咒语。',
      'Improve outputs with reproducible task requirements and examples.',
      'prompting,llm',
      [4, 5, 5, 5],
    ],
    [
      'anthropic-prompt-guide',
      'https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/overview',
      'Claude Prompt Engineering Overview',
      'Claude 提示词设计概览',
      '整理提示词迭代、成功标准与常见设计方法。',
      'An overview of prompt iteration, success criteria and design techniques.',
      '先定义什么算成功，再比较提示词是否有效。',
      'Define success criteria before comparing prompt changes.',
      'prompting,evaluation',
      [4, 5, 5, 5],
    ],
    [
      'gemini-prompt-guide',
      'https://ai.google.dev/gemini-api/docs/prompting-strategies',
      'Gemini Prompt Design Strategies',
      'Gemini 提示词设计策略',
      '通过官方示例理解清晰任务、样例和多模态输入。',
      'Official examples for clear tasks, examples and multimodal inputs.',
      '比较不同模型的输入习惯，避免只记单一产品技巧。',
      'Compare input practices across models instead of memorizing one product.',
      'prompting,multimodal',
      [4, 4, 5, 5],
    ],
    [
      'ollama-quickstart',
      'https://docs.ollama.com/quickstart',
      'Ollama Quickstart',
      'Ollama 本地模型快速入门',
      '安装并运行本地模型，学习基础调用方式。',
      'Install and run local models and learn basic invocation patterns.',
      '第一次体验模型在自己的设备上运行；按硬件选模型。',
      'Try running models on your own hardware and choose models accordingly.',
      'local-ai,inference',
      [4, 5, 5, 5],
    ],
    [
      'hf-model-cards',
      'https://huggingface.co/docs/hub/model-cards',
      'Hugging Face Model Cards',
      '如何阅读与编写模型卡',
      '了解模型用途、训练背景、局限和使用说明。',
      'Understand intended uses, training context, limitations and usage notes.',
      '下载模型前先判断它是否适合任务与部署条件。',
      'Assess a model before downloading or deploying it.',
      'evaluation,ai-literacy',
      [4, 4, 4, 5],
    ],
    [
      'openai-evals-guide',
      'https://developers.openai.com/api/docs/guides/evaluation-best-practices',
      'Evaluation Best Practices',
      'AI 应用评估实践指南',
      '用测试样本、评价标准和持续评估衡量模型输出。',
      'Measure model outputs with datasets, criteria and repeated evaluation.',
      '避免凭几次漂亮演示就认为应用可靠。',
      'Evaluate reliability beyond a few convincing demos.',
      'evaluation,llm',
      [4, 4, 5, 5],
    ],
    [
      'mcp-introduction',
      'https://modelcontextprotocol.io/docs/getting-started/intro',
      'Model Context Protocol Introduction',
      'MCP 协议入门',
      '了解 AI 应用连接外部工具与数据的标准接口。',
      'Understand a standard interface for connecting AI apps with tools and data.',
      '先弄清客户端、服务端和授权边界，再安装工具。',
      'Understand clients, servers and authorization before connecting tools.',
      'agents,tools',
      [4, 4, 4, 5],
    ],
  ]),
  ...makeBeginnerGroup('repo', [
    [
      'openwebui-repo',
      'https://github.com/open-webui/open-webui',
      'Open WebUI',
      'Open WebUI 自托管交互界面',
      '为模型提供可自托管的网页交互界面。',
      'A self-hostable web interface for model interaction.',
      '搭建自己的使用入口，同时了解账号与部署设置。',
      'Build your own interface and learn deployment and account settings.',
      'local-ai,apps',
      [3, 4, 5, 5],
    ],
    [
      'comfyui-repo',
      'https://github.com/Comfy-Org/ComfyUI',
      'ComfyUI',
      'ComfyUI 节点式生成工作流',
      '用节点连接生成式视觉模型与处理步骤。',
      'Connect generative vision models and processing steps with nodes.',
      '把生图流程拆成可以观察和复用的组件。',
      'Break image generation into visible, reusable components.',
      'vision,diffusion,workflow',
      [3, 3, 5, 5],
    ],
    [
      'dify-repo',
      'https://github.com/langgenius/dify',
      'Dify',
      'Dify AI 应用平台',
      '通过可视化工作流组织模型、知识与工具。',
      'Organize models, knowledge and tools through visual workflows.',
      '适合先构建应用原型，再理解背后的各个环节。',
      'Prototype an app and then inspect its underlying stages.',
      'apps,workflow,rag',
      [4, 4, 5, 5],
    ],
    [
      'whisper-repo',
      'https://github.com/openai/whisper',
      'Whisper',
      'Whisper 语音识别',
      '提供语音识别模型与参考推理代码。',
      'Speech recognition models and reference inference code.',
      '以转写任务进入音频 AI，并观察语言和噪声的影响。',
      'Start audio AI with transcription and examine language and noise effects.',
      'audio,inference',
      [4, 4, 5, 5],
    ],
  ]),
  ...makeBeginnerGroup('tool', [
    [
      'chatgpt-tool',
      'https://chatgpt.com/',
      'ChatGPT',
      'ChatGPT 通用 AI 助手',
      '体验文本、多模态与任务协作的对话入口。',
      'A conversational interface for text, multimodal and task assistance.',
      '用同一真实任务反复验证输出；核对来源与事实。',
      'Evaluate it on a real task and verify sources and facts.',
      'ai-literacy,chat',
      [4, 5, 5, 5],
    ],
    [
      'claude-tool',
      'https://claude.ai/',
      'Claude',
      'Claude AI 助手',
      '用于写作、分析与编程的对话式工具。',
      'A conversational tool for writing, analysis and coding.',
      '与其他工具使用相同输入比较效果和限制。',
      'Compare results and limitations using the same inputs across tools.',
      'chat,coding',
      [4, 5, 5, 5],
    ],
    [
      'gemini-tool',
      'https://gemini.google.com/',
      'Gemini',
      'Gemini AI 助手',
      '体验 Google 的通用与多模态助手。',
      'Explore Google’s general-purpose and multimodal assistant.',
      '用图片、文档和文字任务理解多模态交互。',
      'Explore multimodal interaction through images, documents and text.',
      'chat,multimodal',
      [4, 5, 5, 5],
    ],
    [
      'perplexity-tool',
      'https://www.perplexity.ai/',
      'Perplexity',
      'Perplexity 搜索问答',
      '体验带有来源链接的搜索与回答流程。',
      'Explore search and answers accompanied by source links.',
      '练习从回答回到原始来源，检验引用是否支持结论。',
      'Return to original sources and check whether citations support claims.',
      'search,ai-literacy',
      [3, 5, 5, 5],
    ],
    [
      'notebooklm-tool',
      'https://notebooklm.google/',
      'NotebookLM',
      'NotebookLM 资料学习助手',
      '围绕提供的资料进行整理、提问与学习。',
      'Organize, question and study a supplied collection of materials.',
      '从你熟悉的资料开始，比较摘要与原文是否一致。',
      'Start with familiar materials and compare summaries with the originals.',
      'learning,rag',
      [4, 5, 5, 5],
    ],
    [
      'aistudio-tool',
      'https://aistudio.google.com/',
      'Google AI Studio',
      'Google AI Studio 模型实验台',
      '在浏览器中试验模型输入与应用原型。',
      'Experiment with model inputs and application prototypes in a browser.',
      '认识聊天界面之外的开发与参数调试方式。',
      'Explore development and parameter experimentation beyond chat interfaces.',
      'apps,prompting',
      [4, 4, 5, 5],
    ],
    [
      'cursor-tool',
      'https://cursor.com/',
      'Cursor',
      'Cursor AI 编程编辑器',
      '在编辑器中体验 AI 辅助理解、修改与生成代码。',
      'Use AI to understand, edit and generate code in an editor.',
      '从小型可测试修改开始，逐行审查生成代码。',
      'Start with small testable changes and review generated code.',
      'coding,tools',
      [3, 4, 5, 5],
    ],
    [
      'runway-tool',
      'https://runwayml.com/',
      'Runway',
      'Runway 生成式视频工具',
      '体验生成式视觉与视频创作工具。',
      'Explore generative visual and video creation tools.',
      '用短场景测试镜头、运动和角色一致性的局限。',
      'Test motion, framing and character consistency with short scenes.',
      'video,multimodal',
      [3, 4, 5, 5],
    ],
    [
      'midjourney-tool',
      'https://www.midjourney.com/',
      'Midjourney',
      'Midjourney 图像生成工具',
      '通过文字与参考素材探索生成式图像。',
      'Explore image generation with text and reference material.',
      '练习构图、风格与参考约束，同时检查结果偏差。',
      'Practice composition, style and reference constraints while checking deviations.',
      'vision,prompting',
      [3, 4, 4, 5],
    ],
  ]),
  ...makeBeginnerGroup('article', [
    [
      'illustrated-transformer',
      'https://jalammar.github.io/illustrated-transformer/',
      'The Illustrated Transformer',
      '图解 Transformer',
      '用图解逐步说明注意力与 Transformer 的组成。',
      'A visual walkthrough of attention and Transformer components.',
      '在阅读原论文之前建立空间和数据流的直觉。',
      'Build intuition for data flow before reading the original paper.',
      'transformer,llm',
      [5, 5, 2, 4],
    ],
    [
      'anthropic-effective-agents',
      'https://www.anthropic.com/research/building-effective-agents',
      'Building Effective Agents',
      '构建有效的智能体',
      '介绍工作流、智能体与常见组件组织方式。',
      'Discusses workflows, agents and common component patterns.',
      '理解什么时候简单工作流已经足够。',
      'Learn when a simpler workflow is sufficient.',
      'agents,apps',
      [5, 4, 4, 5],
    ],
  ]),
]
