import type { BeginnerSeed } from '@resonance/schema'
import { makeBeginnerGroup } from './catalog.ts'
import { beginnerLocalTools } from './local-tools.ts'

/** Initial discovery pool. These are useful existing resources, not claims of new releases.
 * No publication date is invented; daily candidates may replace every one of these entries.
 */
const carriedDiscoveryCatalog: BeginnerSeed[] = [
  ...makeBeginnerGroup('course', [
    [
      'hf-audio-course',
      'https://huggingface.co/learn/audio-course/chapter0/introduction',
      'Hugging Face Audio Course',
      'Hugging Face 音频 AI 课程',
      '介绍音频数据、语音识别与语音生成的工作流。',
      'Explore audio data, speech recognition and speech generation workflows.',
      '想做语音应用时，先理解采样率、音频表示和任务区别。',
      'Understand sampling, audio representations and task differences before building voice apps.',
      'audio,python',
      [4, 4, 4, 5],
    ],
  ]),
  ...makeBeginnerGroup('guide', [
    [
      'numpy-beginners',
      'https://numpy.org/doc/stable/user/absolute_beginners.html',
      'NumPy: the Absolute Basics',
      'NumPy 零基础指南',
      '了解数组、形状、索引与数值计算。',
      'Understand arrays, shapes, indexing and numerical operations.',
      '理解张量前先熟悉数组，减少形状错误。',
      'Get comfortable with arrays before tensors and shape debugging.',
      'python,math,data',
      [3, 5, 4, 5],
    ],
    [
      'pandas-intro',
      'https://pandas.pydata.org/docs/getting_started/intro_tutorials/',
      'pandas Introductory Tutorials',
      'pandas 入门教程',
      '学习表格读取、清洗、筛选、合并与统计。',
      'Learn table loading, cleaning, filtering, merging and aggregation.',
      '把真实数据整理成可以分析和训练的输入。',
      'Prepare real-world data for analysis and training.',
      'python,data',
      [3, 5, 5, 5],
    ],
    [
      'datasets-quickstart',
      'https://huggingface.co/docs/datasets/quickstart',
      'Datasets Quickstart',
      'Hugging Face 数据集快速入门',
      '介绍加载、检查和处理机器学习数据集。',
      'Load, inspect and process machine learning datasets.',
      '避免把数据准备视为模型训练之外的小事。',
      'Treat data preparation as part of the learning workflow.',
      'data,python',
      [3, 4, 5, 5],
    ],
    [
      'llamaindex-starter',
      'https://developers.llamaindex.ai/python/framework/getting_started/starter_example/',
      'LlamaIndex Starter Tutorial',
      'LlamaIndex 文档问答入门',
      '从读取文档、建立索引到检索后回答。',
      'Load documents, build an index and answer after retrieval.',
      '通过一个小项目理解 RAG 各环节的作用。',
      'Understand the stages of RAG through a small project.',
      'rag,apps',
      [4, 4, 5, 5],
    ],
  ]),
  ...makeBeginnerGroup('repo', [
    [
      'diffusers-repo',
      'https://github.com/huggingface/diffusers',
      'Diffusers',
      'Diffusers 扩散模型库',
      '提供扩散模型的推理与训练组件。',
      'Inference and training components for diffusion models.',
      '理解图像生成流水线以及不同组件的职责。',
      'Explore image generation pipelines and their components.',
      'diffusion,vision',
      [3, 3, 5, 5],
    ],
    [
      'sentence-transformers-repo',
      'https://github.com/huggingface/sentence-transformers',
      'Sentence Transformers',
      'Sentence Transformers 语义向量',
      '把文本编码为向量，用于相似度、搜索和检索。',
      'Encode text as vectors for similarity, search and retrieval.',
      '动手理解 embedding，而不只记住这个术语。',
      'Understand embeddings by building with them.',
      'embeddings,rag',
      [4, 4, 5, 5],
    ],
    [
      'llamacpp-repo',
      'https://github.com/ggml-org/llama.cpp',
      'llama.cpp',
      'llama.cpp 本地推理',
      '使用 C/C++ 在多种硬件上运行语言模型。',
      'Run language models on varied hardware with C/C++.',
      '了解量化、本地推理与硬件约束的实际含义。',
      'Explore quantization, local inference and hardware constraints.',
      'local-ai,inference',
      [4, 3, 5, 5],
    ],
    [
      'flowise-repo',
      'https://github.com/FlowiseAI/Flowise',
      'Flowise',
      'Flowise 可视化 AI 工作流',
      '使用可视化界面搭建 AI 应用流程。',
      'Build AI application flows through a visual interface.',
      '观察输入、模型和工具之间的数据如何流动。',
      'Observe data flowing between inputs, models and tools.',
      'apps,workflow',
      [3, 4, 5, 5],
    ],
  ]),
  ...makeBeginnerGroup('tool', [
    [
      'copilot-tool',
      'https://github.com/features/copilot',
      'GitHub Copilot',
      'GitHub Copilot 编程助手',
      '体验代码补全、问答和开发辅助工作流。',
      'Explore code completion, questions and development assistance.',
      '观察它在哪些任务省时、哪些任务仍需人工验证。',
      'Observe where assistance saves time and where manual verification remains necessary.',
      'coding,tools',
      [3, 5, 5, 5],
    ],
  ]),
]

export const beginnerDiscoveryCatalog: BeginnerSeed[] = [
  ...carriedDiscoveryCatalog,
  ...beginnerLocalTools,
  ...makeBeginnerGroup('guide', [
    [
      'claude-code-quickstart',
      'https://code.claude.com/docs/en/quickstart',
      'Claude Code Quickstart',
      'Claude Code 实战入门',
      '从安装、理解项目到修改代码与运行测试，完成一次 AI 编程流程。',
      'Complete an AI coding workflow from setup and project exploration to code changes and tests.',
      '用一个可验证的小改动练习协作。',
      'Practice collaboration through one verifiable small change.',
      'coding,agents',
      [4, 5, 5, 5],
    ],
    [
      'n8n-ai-workflow',
      'https://docs.n8n.io/build/integrate-ai',
      'n8n AI Workflows',
      'n8n AI 工作流指南',
      '把模型、工具和记忆接入可视化自动化流程。',
      'Connect models, tools and memory in visual automation workflows.',
      '把一次聊天变成可以重复执行的任务。',
      'Turn a chat task into a repeatable workflow.',
      'automation,agents',
      [4, 4, 5, 5],
    ],
    [
      'lmstudio-guide',
      'https://lmstudio.ai/docs/app',
      'LM Studio App Guide',
      'LM Studio 本地模型指南',
      '通过桌面界面下载模型、开始对话并了解本地运行方式。',
      'Download models and chat through a desktop interface while learning local execution.',
      '适合不想先配置命令行的本地模型使用者。',
      'A starting point for local models without beginning in a terminal.',
      'local,llm',
      [4, 5, 5, 5],
    ],
    [
      'anythingllm-guide',
      'https://docs.anythingllm.com/',
      'AnythingLLM Documentation',
      'AnythingLLM 文档问答入门',
      '连接模型和自己的文档，搭建可使用的知识问答空间。',
      'Connect models and your documents to create a knowledge chat workspace.',
      '用自己的资料检验检索问答是否真的有帮助。',
      'Test retrieval against documents you know well.',
      'rag,documents',
      [4, 4, 5, 5],
    ],
    [
      'openrouter-quickstart',
      'https://openrouter.ai/docs/quickstart',
      'OpenRouter Quickstart',
      'OpenRouter 多模型调用入门',
      '通过统一接口尝试不同模型并接入已有应用。',
      'Try different models through one interface and connect them to an app.',
      '适合做小规模模型比较，先了解费用和接口条件。',
      'Useful for small model comparisons after checking access and costs.',
      'api,llm',
      [3, 4, 5, 5],
    ],
    [
      'hf-spaces-guide',
      'https://huggingface.co/docs/hub/spaces-overview',
      'Hugging Face Spaces Overview',
      'Hugging Face Spaces 应用展示指南',
      '发布可交互的机器学习演示并分享给其他人试用。',
      'Publish interactive machine learning demos that others can try.',
      '把本地实验变成别人能打开的应用入口。',
      'Turn a local experiment into a shareable app.',
      'deployment,demo',
      [3, 5, 5, 5],
    ],
    [
      'firecrawl-guide',
      'https://docs.firecrawl.dev/introduction',
      'Firecrawl Documentation',
      'Firecrawl 网页数据指南',
      '将网页提取为适合后续检索和模型处理的数据。',
      'Extract web pages into data suitable for retrieval and model workflows.',
      '解决给模型准备网页资料的具体步骤。',
      'Learn a concrete way to prepare web sources for a model.',
      'data,rag',
      [3, 4, 5, 5],
    ],
    [
      'promptfoo-guide',
      'https://www.promptfoo.dev/docs/getting-started/',
      'Promptfoo Getting Started',
      'Promptfoo 提示词测试入门',
      '用可重复的测试集比较提示词和模型输出。',
      'Compare prompts and model outputs with repeatable test cases.',
      '把感觉更好变成可检查的输出差异。',
      'Replace vague impressions with inspectable output differences.',
      'evaluation,prompting',
      [4, 4, 5, 5],
    ],
    [
      'langfuse-guide',
      'https://langfuse.com/docs',
      'Langfuse Documentation',
      'Langfuse 应用观察指南',
      '记录模型应用的调用过程、提示词和评估结果。',
      'Trace model calls, prompts and evaluation results in an application.',
      '排查多步任务哪里出错以及成本花在哪里。',
      'Find where a multi-step task fails and where cost accumulates.',
      'evaluation,observability',
      [3, 4, 5, 5],
      true,
    ],
    [
      'pydantic-ai-guide',
      'https://pydantic.dev/docs/ai/overview/',
      'Pydantic AI Documentation',
      'Pydantic AI 结构化智能体指南',
      '用 Python 定义工具、输出结构和智能体流程。',
      'Define tools, structured outputs and agent workflows in Python.',
      '适合已经会调用模型、需要可检查输出的人。',
      'Useful after basic model calls when output needs validation.',
      'agents,python',
      [4, 4, 5, 5],
      true,
    ],
  ]),
  ...makeBeginnerGroup('repo', [
    [
      'docling-repo',
      'https://github.com/docling-project/docling',
      'Docling',
      'Docling 文档解析',
      '把 PDF、办公文档和图片转换为模型更易处理的结构化内容。',
      'Convert PDFs, office documents and images into structured model-ready content.',
      '先把文档读对，再做总结或知识库。',
      'Improve document extraction before summarization or retrieval.',
      'documents,rag',
      [4, 4, 5, 5],
    ],
    [
      'marker-repo',
      'https://github.com/datalab-to/marker',
      'Marker',
      'Marker PDF 转换',
      '将 PDF 转成 Markdown 或 JSON，供搜索和后续处理使用。',
      'Convert PDFs to Markdown or JSON for search and downstream processing.',
      '用真实复杂页面比较表格和段落转换结果。',
      'Compare table and paragraph extraction on real pages.',
      'documents,pdf',
      [3, 4, 5, 5],
    ],
    [
      'paddleocr-repo',
      'https://github.com/PaddlePaddle/PaddleOCR',
      'PaddleOCR',
      'PaddleOCR 文字与文档识别',
      '识别图片和扫描文档中的文字及布局。',
      'Recognize text and layout in images and scanned documents.',
      '给扫描资料建立可搜索的文字底稿。',
      'Create searchable text from scanned material.',
      'ocr,documents',
      [4, 4, 5, 5],
    ],
    [
      'whisperx-repo',
      'https://github.com/m-bain/whisperX',
      'WhisperX',
      'WhisperX 时间轴转写',
      '在语音转写中加入词级时间戳与说话人区分流程。',
      'Add word-level timestamps and speaker diarization to speech transcription.',
      '适合需要对齐音频的字幕和采访整理。',
      'Useful for subtitles and interviews that need audio alignment.',
      'audio,transcription',
      [3, 3, 5, 5],
      true,
    ],
    [
      'subtitleedit-repo',
      'https://github.com/SubtitleEdit/subtitleedit',
      'Subtitle Edit',
      'Subtitle Edit 字幕工作台',
      '在字幕编辑器中整理、校对和同步字幕，并使用语音识别功能。',
      'Edit, proofread and synchronize subtitles with speech recognition support.',
      '自动转写后仍需要可以逐句修正的工具。',
      'Keep a practical way to correct automatic transcripts line by line.',
      'audio,subtitles',
      [3, 4, 5, 5],
    ],
    [
      'kokoro-repo',
      'https://github.com/hexgrad/kokoro',
      'Kokoro',
      'Kokoro 语音合成',
      '用可运行的语音合成项目把文字转为音频。',
      'Turn text into audio with a runnable speech synthesis project.',
      '先制作短旁白，比较发音与停顿。',
      'Begin with a short narration and inspect pronunciation and pauses.',
      'audio,tts',
      [3, 4, 5, 5],
    ],
    [
      'sherpa-onnx-repo',
      'https://github.com/k2-fsa/sherpa-onnx',
      'sherpa-onnx',
      'sherpa-onnx 离线语音工具',
      '在本地集成语音识别、语音合成等音频能力。',
      'Integrate local speech recognition, synthesis and related audio capabilities.',
      '适合需要离线或设备端语音功能的开发者。',
      'Useful for offline or on-device speech applications.',
      'audio,local',
      [4, 3, 4, 5],
      true,
    ],
    [
      'aider-repo',
      'https://github.com/Aider-AI/aider',
      'Aider',
      'Aider 终端结对编程',
      '在已有 Git 项目里与模型协作修改代码。',
      'Collaborate with a model on code changes in an existing Git project.',
      '通过差异和测试检查模型改了什么。',
      'Use diffs and tests to inspect model changes.',
      'coding,agents',
      [4, 4, 5, 5],
    ],
    [
      'continue-repo',
      'https://github.com/continuedev/continue',
      'Continue',
      'Continue 编程智能体',
      '把 AI 编程辅助接入开发工作流。',
      'Bring an AI coding agent into a development workflow.',
      '适合比较不同模型与已有开发工具的配合。',
      'Compare how models fit an existing development setup.',
      'coding,agents',
      [3, 4, 5, 5],
    ],
    [
      'cline-repo',
      'https://github.com/cline/cline',
      'Cline',
      'Cline 编程助手',
      '在开发环境里让智能体读取项目并完成可审查的修改。',
      'Let an agent explore a project and produce reviewable code changes.',
      '从小任务练习文件修改与执行步骤的审查。',
      'Practice reviewing edits and execution steps on a small task.',
      'coding,agents',
      [3, 4, 5, 5],
    ],
    [
      'opencode-repo',
      'https://github.com/anomalyco/opencode',
      'OpenCode',
      'OpenCode 开源编程智能体',
      '通过开源编程智能体在项目中使用模型。',
      'Use models in a project through an open-source coding agent.',
      '适合想比较不同模型编程工作流的人。',
      'Useful for comparing coding workflows across models.',
      'coding,agents',
      [3, 4, 5, 5],
    ],
    [
      'goose-repo',
      'https://github.com/aaif-goose/goose',
      'Goose',
      'Goose 可扩展任务智能体',
      '把模型与工具连接起来，执行开发和日常多步任务。',
      'Connect models and tools for development and multi-step tasks.',
      '用具体小任务了解工具接入和执行边界。',
      'Explore tool integration and execution boundaries on a concrete task.',
      'agents,automation',
      [4, 3, 5, 5],
    ],
    [
      'codex-repo',
      'https://github.com/openai/codex',
      'Codex CLI',
      'Codex 命令行编程智能体',
      '在终端中理解项目、修改代码并检查结果。',
      'Explore projects, edit code and inspect results from the terminal.',
      '把需求、代码差异和测试串成一次完整协作。',
      'Connect a request, a code diff and tests in one workflow.',
      'coding,agents',
      [4, 4, 5, 5],
    ],
    [
      'gemini-cli-repo',
      'https://github.com/google-gemini/gemini-cli',
      'Gemini CLI',
      'Gemini CLI 终端助手',
      '在终端中使用 Gemini 执行编程与工具任务。',
      'Use Gemini for coding and tool tasks in the terminal.',
      '适合已有终端习惯的人从一个项目开始。',
      'Start with one project if you already use a terminal.',
      'coding,agents',
      [3, 4, 5, 5],
    ],
    [
      'ragflow-repo',
      'https://github.com/infiniflow/ragflow',
      'RAGFlow',
      'RAGFlow 知识检索应用',
      '把文档解析、检索和问答组合成知识应用。',
      'Combine document parsing, retrieval and question answering.',
      '对照原文检查知识库答案和检索结果。',
      'Check knowledge-base answers against retrieved sources.',
      'rag,documents',
      [4, 3, 5, 5],
      true,
    ],
    [
      'maxkb-repo',
      'https://github.com/1Panel-dev/MaxKB',
      'MaxKB',
      'MaxKB 智能体应用平台',
      '通过可视化平台构建知识问答和智能体应用。',
      'Build knowledge chat and agent applications through a visual platform.',
      '适合从内部资料问答开始验证场景。',
      'Start by testing questions against your own reference material.',
      'rag,agents',
      [3, 4, 5, 5],
    ],
    [
      'fastgpt-repo',
      'https://github.com/labring/FastGPT',
      'FastGPT',
      'FastGPT 知识库与工作流',
      '组合知识库检索与可视化 AI 工作流。',
      'Combine knowledge retrieval with visual AI workflows.',
      '先完成一个资料问答，再增加处理步骤。',
      'Build a document question-answering task before adding steps.',
      'rag,automation',
      [3, 4, 5, 5],
    ],
    [
      'crawl4ai-repo',
      'https://github.com/unclecode/crawl4ai',
      'Crawl4AI',
      'Crawl4AI 网页内容提取',
      '将网页内容整理成适合模型处理的数据。',
      'Prepare web content for model-based processing.',
      '适合为阅读和检索任务准备公开网页资料。',
      'Prepare public web sources for reading and retrieval workflows.',
      'data,rag',
      [3, 3, 5, 5],
      true,
    ],
    [
      'open-notebook-repo',
      'https://github.com/lfnovo/open-notebook',
      'Open Notebook',
      'Open Notebook 资料研究工作台',
      '自托管资料整理、问答和内容研究工作流。',
      'Self-host source organization, question answering and research workflows.',
      '适合希望自己管理资料与模型选择的人。',
      'Useful when you want control over sources and model selection.',
      'documents,research',
      [3, 4, 5, 5],
    ],
    [
      'mcp-inspector-repo',
      'https://github.com/modelcontextprotocol/inspector',
      'MCP Inspector',
      'MCP Inspector 工具调试',
      '用可视化界面检查 MCP 服务提供的工具和响应。',
      'Inspect an MCP server and its tool responses through a visual interface.',
      '连接失败时先看实际请求与返回值。',
      'Inspect actual requests and responses when an integration fails.',
      'mcp,tools',
      [4, 4, 5, 5],
      true,
    ],
    [
      'invokeai-repo',
      'https://github.com/invoke-ai/InvokeAI',
      'InvokeAI',
      'InvokeAI 图像创作工作台',
      '通过可视化界面生成和编辑图像。',
      'Generate and edit images through a visual creative interface.',
      '把生成图片放进可以反复修改的创作流程。',
      'Bring image generation into an iterative editing workflow.',
      'image,creative',
      [3, 4, 5, 5],
    ],
    [
      'krita-ai-repo',
      'https://github.com/Acly/krita-ai-diffusion',
      'Krita AI Diffusion',
      'Krita AI 绘画插件',
      '在 Krita 中结合手工绘画、局部重绘和 AI 生成。',
      'Combine painting, inpainting and AI generation inside Krita.',
      '适合已有画面构图、需要局部修改的创作者。',
      'Useful for creators who want controlled changes to an existing composition.',
      'image,creative',
      [4, 4, 5, 5],
    ],
    [
      'wan2gp-repo',
      'https://github.com/deepbeepmeep/Wan2GP',
      'Wan2GP',
      'Wan2GP 本地视频生成',
      '在本地运行视频和图像生成工作流。',
      'Run video and image generation workflows locally.',
      '先核对显卡与模型要求，再从短片段开始。',
      'Check hardware and model requirements before trying a short clip.',
      'video,local',
      [3, 3, 5, 5],
      true,
    ],
    [
      'jan-repo',
      'https://github.com/janhq/jan',
      'Jan',
      'Jan 本地聊天客户端',
      '通过桌面客户端运行本地模型并对话。',
      'Run and chat with local models through a desktop application.',
      '适合从下载模型到实际对话完整体验本地 AI。',
      'Try the full local-model path from download to conversation.',
      'local,chat',
      [3, 5, 5, 5],
    ],
    [
      'librechat-repo',
      'https://github.com/danny-avila/LibreChat',
      'LibreChat',
      'LibreChat 自托管聊天界面',
      '在统一界面中组织多个模型与聊天工具。',
      'Organize multiple models and chat tools in one self-hosted interface.',
      '适合已有接口、希望自己管理聊天工作台的人。',
      'Useful when you have model access and want to manage the chat workspace.',
      'chat,self-hosting',
      [3, 4, 5, 5],
      true,
    ],
    [
      'cherry-studio-repo',
      'https://github.com/CherryHQ/cherry-studio',
      'Cherry Studio',
      'Cherry Studio AI 工作台',
      '通过桌面工作台连接模型并组织日常 AI 任务。',
      'Connect models and organize everyday AI tasks through a desktop workspace.',
      '减少在不同模型入口间来回切换。',
      'Keep everyday model work in one place.',
      'chat,productivity',
      [3, 5, 5, 5],
    ],
  ]),
  ...makeBeginnerGroup('tool', [
    [
      'elevenlabs-tool',
      'https://elevenlabs.io/',
      'ElevenLabs',
      'ElevenLabs 语音生成',
      '用文字生成语音并尝试音频创作功能。',
      'Generate speech from text and explore audio creation tools.',
      '用一段短旁白检查发音、语气与可编辑性。',
      'Test pronunciation, delivery and editability with a short narration.',
      'audio,tts',
      [3, 5, 5, 5],
    ],
    [
      'descript-tool',
      'https://www.descript.com/',
      'Descript',
      'Descript 文本式音视频编辑',
      '通过转写文本编辑音频和视频内容。',
      'Edit audio and video through their transcripts.',
      '适合采访、播客和讲解视频的初步整理。',
      'Useful for a first pass on interviews, podcasts and explainers.',
      'audio,video',
      [4, 5, 5, 5],
    ],
    [
      'firefly-tool',
      'https://firefly.adobe.com/',
      'Adobe Firefly',
      'Adobe Firefly 创意生成',
      '通过 Adobe 的创作界面生成和编辑视觉内容。',
      'Generate and edit visual content through Adobe creative tools.',
      '从一张可修改的素材开始练习生成式编辑。',
      'Start with one editable asset to practice generative editing.',
      'image,creative',
      [3, 4, 5, 5],
    ],
    [
      'canva-ai-tool',
      'https://www.canva.com/ai/',
      'Canva AI',
      'Canva AI 设计工作台',
      '把 AI 生成内容接入海报、演示和日常设计流程。',
      'Bring AI-generated content into posters, presentations and everyday design.',
      '适合需要把内容排成可交付页面的人。',
      'Useful when generated content needs a finished layout.',
      'design,productivity',
      [3, 5, 5, 5],
    ],
    [
      'ideogram-tool',
      'https://ideogram.ai/',
      'Ideogram',
      'Ideogram 图像生成',
      '通过提示词生成和迭代视觉素材。',
      'Generate and iterate on visual assets from prompts.',
      '用相同构图需求比较多版结果。',
      'Compare variations against the same composition brief.',
      'image,creative',
      [3, 4, 5, 5],
    ],
    [
      'recraft-tool',
      'https://www.recraft.ai/',
      'Recraft',
      'Recraft 设计图像生成',
      '生成适合设计工作流的图像素材。',
      'Generate visual assets for design workflows.',
      '围绕同一风格练习成组素材的一致性。',
      'Practice consistency across a set of assets in one visual style.',
      'image,design',
      [3, 4, 5, 5],
    ],
    [
      'adobe-podcast-tool',
      'https://podcast.adobe.com/',
      'Adobe Podcast',
      'Adobe Podcast 语音整理',
      '使用在线音频工具改善语音录制和处理流程。',
      'Use online audio tools to improve speech recording and processing.',
      '对比处理前后的人声清晰度与失真。',
      'Compare speech clarity and artifacts before and after processing.',
      'audio,productivity',
      [3, 5, 5, 5],
    ],
    [
      'leonardo-tool',
      'https://leonardo.ai/',
      'Leonardo.Ai',
      'Leonardo AI 视觉创作',
      '生成和编辑图像、视频创意素材。',
      'Generate and edit image and video creative assets.',
      '适合通过多轮迭代探索视觉方案。',
      'Explore visual directions through iterative generation.',
      'image,video',
      [3, 4, 5, 5],
    ],
    [
      'suno-tool',
      'https://suno.com/',
      'Suno',
      'Suno 音乐生成',
      '根据文字描述生成音乐并探索不同风格。',
      'Generate music from text descriptions and explore different styles.',
      '先做短音乐草稿，检查结构与情绪是否合适。',
      'Start with a music sketch and check its structure and mood.',
      'audio,music',
      [3, 5, 4, 5],
    ],
    [
      'elicit-tool',
      'https://elicit.com/',
      'Elicit',
      'Elicit 论文检索与整理',
      '围绕研究问题搜索论文并整理证据。',
      'Search papers around a research question and organize evidence.',
      '回到原文核对结论，减少只读模型总结。',
      'Check claims in the original papers rather than relying only on summaries.',
      'research,search',
      [4, 4, 5, 5],
    ],
    [
      'gamma-tool',
      'https://gamma.app/',
      'Gamma',
      'Gamma 演示内容生成',
      '把想法与资料组织成演示文稿或页面初稿。',
      'Turn ideas and source material into presentation or page drafts.',
      '适合先搭结构，再人工检查论点和版面。',
      'Draft a structure before reviewing claims and layout.',
      'presentation,productivity',
      [3, 5, 5, 5],
    ],
    [
      'napkin-tool',
      'https://www.napkin.ai/',
      'Napkin AI',
      'Napkin AI 文字转图解',
      '把文字观点转换成可编辑的图解和视觉表达。',
      'Turn written ideas into diagrams and visual explanations.',
      '适合说明流程、关系和比较，而不只是配装饰图。',
      'Explain processes, relationships and comparisons visually.',
      'diagram,productivity',
      [4, 5, 5, 5],
    ],
    [
      'deepl-write-tool',
      'https://www.deepl.com/en/write',
      'DeepL Write',
      'DeepL Write 写作润色',
      '改写和润色文本，比较措辞、语气与表达方式。',
      'Revise writing and compare phrasing, tone and expression.',
      '逐句核对改写是否保留了原意。',
      'Review each rewrite for preserved meaning.',
      'writing,productivity',
      [3, 5, 5, 5],
    ],
    [
      'v0-tool',
      'https://v0.app/',
      'v0',
      'v0 网页应用原型',
      '从文字需求生成网页界面与应用原型。',
      'Generate web interfaces and application prototypes from a brief.',
      '把生成结果跑起来检查交互，而不只看截图。',
      'Run the result and check interactions, not just its appearance.',
      'coding,prototype',
      [3, 4, 5, 5],
    ],
  ]),
]
