import { makeBeginnerGroup } from './catalog.ts'

/** Official Chinese-language entry points checked on 2026-09-21; not new-release claims or hands-on reviews. */
export const beginnerLocalTools = makeBeginnerGroup('tool', [
  [
    'deepseek-tool',
    'https://chat.deepseek.com/',
    'DeepSeek',
    'DeepSeek 中文 AI 助手',
    '用日常问题练习提问、追问和核对答案。',
    'Practice questions, follow-ups and answer checking in a chat interface.',
    '先用熟悉的问题比较回答，建立验证习惯。',
    'Start with familiar questions to build a habit of checking answers.',
    'chat,chinese,reasoning',
    [3, 5, 5, 5],
  ],
  [
    'kimi-tool',
    'https://www.kimi.com/',
    'Kimi',
    'Kimi AI 助手',
    '从具体任务出发，练习把需求交给 AI 并检查结果。',
    'Practice delegating a concrete task to AI and reviewing its result.',
    '用同一项任务比较需求是否表达清楚。',
    'Use a concrete task to check whether your instructions are clear.',
    'chat,chinese,agents',
    [3, 5, 5, 5],
  ],
  [
    'qianwen-tool',
    'https://www.qianwen.com/',
    'Qianwen',
    '千问 AI 助手',
    '用中文描述问题、补充背景，练习多轮沟通。',
    'Practice multi-turn assistance with Chinese questions and context.',
    '适合从日常写作和问答开始熟悉 AI。',
    'Start with everyday writing and questions to explore AI assistance.',
    'chat,chinese,writing',
    [3, 5, 4, 5],
  ],
  [
    'doubao-tool',
    'https://www.doubao.com/chat/',
    'Doubao',
    '豆包 AI 助手',
    '从日常问答与内容草稿开始尝试 AI 协作。',
    'Try AI collaboration through everyday questions and content drafts.',
    '用简单任务观察补充条件怎样改变回答。',
    'Observe how adding requirements changes the response to a simple task.',
    'chat,chinese,writing',
    [3, 5, 5, 5],
  ],
  [
    'yuanbao-tool',
    'https://yuanbao.tencent.com/',
    'Tencent Yuanbao',
    '腾讯元宝',
    '尝试中文搜索问答，并回到来源核对信息。',
    'Try Chinese search-assisted questions and verify information against sources.',
    '练习区分模型回答和可核查的来源材料。',
    'Practice distinguishing generated answers from verifiable source material.',
    'search,chinese,chat',
    [3, 5, 4, 5],
  ],
  [
    'chatglm-tool',
    'https://chatglm.cn/',
    'Zhipu Qingyan',
    '智谱清言',
    '中文对话入口，可用于练习提问与比较回答。',
    'A Chinese chat entry point for practicing prompts and comparing answers.',
    '同一道问题在不同助手上作答，观察差异并核实。',
    'Compare assistants on the same question and check differences.',
    'chat,chinese',
    [3, 4, 4, 5],
  ],
  [
    'minimax-agent-tool',
    'https://agent.minimaxi.com/',
    'MiniMax Agent',
    'MiniMax Agent 任务助手',
    '把工作拆成具体任务，体验智能体执行与结果检查。',
    'Break work into concrete tasks and review an agent’s execution and output.',
    '从边界清楚的小任务开始，再逐步增加步骤。',
    'Start with a small, well-defined task before adding more steps.',
    'agents,chinese,productivity',
    [3, 4, 5, 5],
  ],
  [
    'hailuo-tool',
    'https://hailuoai.com/',
    'Hailuo AI',
    '海螺 AI 视频创作',
    '尝试视频生成，练习描述动作、镜头与参考画面。',
    'Explore video generation by describing actions, shots and reference imagery.',
    '适合用短镜头练习提示词与成片之间的对应关系。',
    'Use short shots to compare a prompt with its generated result.',
    'video,chinese,creative',
    [3, 4, 5, 5],
  ],
  [
    'jimeng-tool',
    'https://jimeng.jianying.com/',
    'Jimeng AI',
    '即梦 AI 图像与视频创作',
    '从中文提示词或图片开始制作图像与视频。',
    'Create images and video from Chinese prompts or reference images.',
    '练习主体、画面风格和运动描述的组合。',
    'Practice combining subject, visual style and motion descriptions.',
    'image,video,chinese,creative',
    [3, 5, 5, 5],
  ],
  [
    'spark-tool',
    'https://spark.xfyun.cn/',
    'iFlytek Spark',
    '讯飞星火 AI 助手',
    '体验写作、文档问答与录音纪要等办公任务。',
    'Explore writing, document questions and recorded meeting notes.',
    '从真实办公任务练习给背景、定格式和验收结果。',
    'Practice context, output formats and result checking on a real work task.',
    'productivity,chinese,writing',
    [3, 4, 5, 5],
  ],
])
