export const beginnerStrings = {
  zh: {
    title: '入门推荐',
    types: {
      all: '所有类型',
      paper: '论文',
      article: '文章',
      news: '新闻',
      repo: '开源项目',
      tool: '工具',
      guide: '操作手册',
      course: '课程',
      book: '书籍',
    },
    scopes: { all: '全部', resident: '常驻', dynamic: '动态推荐' },
    counts: { resident: '常驻', dynamic: '动态' },
    scopeLabel: '按常驻或动态内容筛选',
    badges: { new: 'NEW', back: '回归' },
    badgeHints: { new: '最近 7 天首次收录，不代表原文刚发布', back: '最近 7 天重新收录' },
    origins: { curated: '常驻', discovered: '动态' },
    search: '搜索资源',
    searchPlaceholder: '搜索工具、文章或知识点',
    recent: '只看新收录',
    typeLabel: '资源类型',
    reset: '清除筛选',
    refresh: '刷新',
    result: '项',
    empty: '暂无匹配资源',
    emptyHelp: '换个关键词或筛选条件。',
    open: '原文',
    added: '收录',
    published: '发布',
    sourceUpdated: '更新',
    untranslated: '原文',
    updated: '更新于',
    dataAsOf: '数据截至',
  },
  en: {
    title: 'Starter picks',
    types: {
      all: 'All types',
      paper: 'Papers',
      article: 'Articles',
      news: 'News',
      repo: 'Open source',
      tool: 'Tools',
      guide: 'Guides',
      course: 'Courses',
      book: 'Books',
    },
    scopes: { all: 'All', resident: 'Essentials', dynamic: 'Rotating' },
    counts: { resident: 'essentials', dynamic: 'rotating' },
    scopeLabel: 'Filter essentials or rotating picks',
    badges: { new: 'NEW', back: 'BACK' },
    badgeHints: { new: 'First added within 7 days; the source may be older', back: 'Returned within the past 7 days' },
    origins: { curated: 'Essential', discovered: 'Rotating' },
    search: 'Search resources',
    searchPlaceholder: 'Search tools, articles or concepts',
    recent: 'Recently added',
    typeLabel: 'Resource type',
    reset: 'Clear filters',
    refresh: 'Refresh',
    result: 'resources',
    empty: 'No matching resources',
    emptyHelp: 'Try another query or filter.',
    open: 'Open resource',
    added: 'Added',
    published: 'Published',
    sourceUpdated: 'Updated',
    untranslated: 'Original',
    updated: 'Updated',
    dataAsOf: 'Data through',
  },
} as const
