/**
 * Seed text for the mock Social and Labs boards: posts from real subreddits and official lab accounts, and official
 * updates from the eleven companies in config.yaml. Fictional sample data for local development only — the generated
 * files live in the git-ignored public/api folder and are replaced by the pipeline's output in CI.
 *
 * `link` ties a post to another mock entity so resonance clusters form: `gh:owner/repo`, `paper:<index>` (PAPERS),
 * `lab:<id>` (LAB_POSTS), `news:<index>` (NEWS_ANCHORS).
 */
import type { Category, LabKind } from '@resonance/schema'

/** `[subreddit, flair, title, zh title, category, link?, day offset from the end (-1 = last edition)?]` */
export type RedditSeed = [string, string, string, string, Category, string?, number?]

export const REDDIT: RedditSeed[] = [
  [
    'LocalLLaMA',
    'New Model',
    'DeepSeek-V4 weights are up on Hugging Face — 1M context, MIT license',
    'DeepSeek-V4 权重已上架 Hugging Face：百万上下文，MIT 许可',
    'release',
    'gh:deepseek-ai/deepseek-v4',
    -3,
  ],
  [
    'LocalLLaMA',
    'Resources',
    'Qwen3-Coder-Next at Q4 runs at 48 tok/s on a single 4090 — full benchmark sheet inside',
    'Qwen3-Coder-Next 的 Q4 量化在单张 4090 上跑到 48 tok/s，附完整测评表',
    'engineering',
    'gh:qwenlm/qwen3-coder',
    -1,
  ],
  [
    'LocalLLaMA',
    'Discussion',
    'llama.cpp just merged speculative decoding for MoE models — 1.8× on my M3 Max',
    'llama.cpp 合并了 MoE 模型的推测解码，我的 M3 Max 上提速 1.8 倍',
    'tool',
    'gh:ggml-org/llama.cpp',
  ],
  [
    'LocalLLaMA',
    'News',
    'Kimi K2.5 open weights released with a 256K context window',
    'Kimi K2.5 开放权重发布，支持 256K 上下文',
    'release',
    'lab:kimi-k25',
  ],
  [
    'LocalLLaMA',
    'Discussion',
    'What is your daily-driver local model for coding in September 2026?',
    '2026 年 9 月，你日常写代码用的本地模型是哪个？',
    'discussion',
  ],
  [
    'LocalLLaMA',
    'Resources',
    'I benchmarked 14 quantisation formats on the same 70B model so you do not have to',
    '我在同一个 70B 模型上测了 14 种量化格式，省得你们再测',
    'engineering',
  ],
  [
    'LocalLLaMA',
    'New Model',
    'GLM-5 Air: a 106B MoE that fits on two 3090s',
    'GLM-5 Air：两张 3090 就能装下的 106B MoE',
    'release',
    'lab:glm5-air',
  ],
  [
    'LocalLLaMA',
    'Discussion',
    'Unsloth now fine-tunes 70B on a single 48 GB card — tried it on my own data',
    'Unsloth 现在能在单张 48GB 显卡上微调 70B，我用自己的数据试了',
    'tool',
    'gh:unslothai/unsloth',
  ],
  [
    'MachineLearning',
    'Research',
    '[R] Echo Attention: exact softmax attention in linear time via resonant state caching',
    '[R] Echo Attention：借助共振状态缓存实现线性时间的精确 softmax 注意力',
    'research',
    'paper:0',
  ],
  [
    'MachineLearning',
    'Discussion',
    '[D] Are web-agent benchmarks measuring memorisation? Thoughts on the contamination audit',
    '[D] 网页智能体基准测的是记忆力吗？谈谈那篇数据污染审计',
    'discussion',
    'paper:3',
  ],
  [
    'MachineLearning',
    'Project',
    '[P] nanochat: I trained the $100 ChatGPT end to end — notes and loss curves',
    '[P] nanochat：我从头到尾训练了“100 美元版 ChatGPT”，附笔记和损失曲线',
    'engineering',
    'gh:karpathy/nanochat',
  ],
  [
    'MachineLearning',
    'Discussion',
    '[D] New reviewer guidelines for LLM-assisted reviews at NeurIPS 2026',
    '[D] NeurIPS 2026 关于 LLM 辅助审稿的新指南',
    'policy',
  ],
  [
    'MachineLearning',
    'Research',
    '[R] Sparse autoencoders find a refusal direction that transfers across model families',
    '[R] 稀疏自编码器找到了可跨模型家族迁移的“拒答方向”',
    'research',
  ],
  [
    'MachineLearning',
    'Discussion',
    '[D] Is anyone still training dense models above 30B?',
    '[D] 还有人在训练 30B 以上的稠密模型吗？',
    'discussion',
  ],
  [
    'singularity',
    'AI',
    'Anthropic announces Claude Opus 5 with a 2M-token context window',
    'Anthropic 发布 Claude Opus 5，上下文窗口达 200 万 token',
    'release',
    'lab:claude-opus5',
    -1,
  ],
  [
    'singularity',
    'AI',
    'Gemini 3 Ultra tops the LMArena leaderboard by 40 points',
    'Gemini 3 Ultra 以 40 分优势登顶 LMArena 排行榜',
    'industry',
    'lab:gemini3-ultra',
  ],
  [
    'singularity',
    'Discussion',
    'The gap between open and closed models is now under three months',
    '开源与闭源模型的差距已缩小到三个月以内',
    'discussion',
  ],
  [
    'singularity',
    'AI',
    'AlphaProof 2 solves 5 of 6 problems from this year’s IMO shortlist',
    'AlphaProof 2 解出今年 IMO 候选题中的 5 道',
    'research',
    'lab:alphaproof2',
  ],
  [
    'OpenAI',
    'News',
    'Codex now runs tasks in parallel cloud sandboxes for Plus users',
    'Codex 现已为 Plus 用户在并行云端沙箱中运行任务',
    'product',
    'lab:codex-parallel',
  ],
  [
    'OpenAI',
    'Discussion',
    'GPT-5.5 feels noticeably better at long refactors — anyone else?',
    'GPT-5.5 在长重构任务上明显更强了，还有人有同感吗？',
    'discussion',
  ],
  [
    'OpenAI',
    'News',
    'GPT-5.5 is rolling out to all ChatGPT users',
    'GPT-5.5 正在向所有 ChatGPT 用户推送',
    'release',
    'lab:gpt55',
  ],
  [
    'ClaudeAI',
    'News',
    'Claude Code background agents are now generally available',
    'Claude Code 后台智能体全面上线',
    'product',
    'lab:claude-bg',
  ],
  [
    'ClaudeAI',
    'Productivity',
    'My workflow for reviewing 40 PRs a day with Claude Code subagents',
    '我用 Claude Code 子智能体每天审 40 个 PR 的工作流',
    'engineering',
  ],
  [
    'ClaudeAI',
    'Praise',
    'Opus 5 refactored a 20-year-old Perl codebase and the tests still pass',
    'Opus 5 重构了一个 20 年的 Perl 代码库，测试居然全部通过',
    'discussion',
    'lab:claude-opus5',
    -1,
  ],
  [
    'artificial',
    'News',
    'EU publishes the first code of practice for general-purpose AI model providers',
    '欧盟发布首份通用 AI 模型提供者行为准则',
    'policy',
  ],
  [
    'artificial',
    'News',
    'NVIDIA and Mistral announce a sovereign AI compute partnership in France',
    '英伟达与 Mistral 宣布在法国合作建设主权 AI 算力',
    'industry',
    'lab:mistral-nvidia',
  ],
  [
    'LLMDevs',
    'Discussion',
    'Prompt caching cut our agent bill by 62% — here is what actually worked',
    '提示缓存让我们的智能体账单降了 62%，这些做法真正有效',
    'engineering',
  ],
  [
    'LLMDevs',
    'Tools',
    'Open-sourced our MCP gateway: auth, rate limits and audit logs for 40+ servers',
    '开源了我们的 MCP 网关：为 40 多个服务器提供鉴权、限流和审计日志',
    'tool',
    'gh:modelcontextprotocol/servers',
  ],
  [
    'LLMDevs',
    'Discussion',
    'Evals before prompts: how we stopped shipping regressions',
    '先写评测再写提示词：我们如何不再上线回归问题',
    'engineering',
  ],
  [
    'DeepSeek',
    'News',
    'DeepSeek API prices drop 50% during off-peak hours starting today',
    'DeepSeek API 从今天起夜间时段价格下调 50%',
    'industry',
    'lab:deepseek-offpeak',
  ],
  [
    'DeepSeek',
    'Discussion',
    'DeepSeek-V4 vs Qwen3-Max on real coding tasks: my week of testing',
    'DeepSeek-V4 与 Qwen3-Max 实战编程对比：我测了一周',
    'discussion',
  ],
  [
    'GeminiAI',
    'News',
    'Gemini CLI gets native MCP support and a free 1,000-request daily tier',
    'Gemini CLI 支持原生 MCP，并提供每日 1000 次免费请求',
    'product',
    'gh:google-gemini/gemini-cli',
  ],
  [
    'GeminiAI',
    'Discussion',
    'Deep Research reading my Drive is either magic or terrifying',
    'Deep Research 能读我的云端硬盘了，不知是神奇还是可怕',
    'discussion',
    'lab:gemini-drive',
  ],
  [
    'StableDiffusion',
    'Workflow Included',
    'Wan 3.0 image-to-video in ComfyUI: 8 s clips on 16 GB VRAM',
    'ComfyUI 中的 Wan 3.0 图生视频：16GB 显存生成 8 秒片段',
    'tool',
    'gh:comfyanonymous/comfyui',
  ],
  [
    'StableDiffusion',
    'News',
    'FLUX.2 schnell released under Apache-2.0',
    'FLUX.2 schnell 以 Apache-2.0 许可发布',
    'release',
  ],
  [
    'mlscaling',
    'Research',
    'Compute-optimal scaling for mixture-of-experts, revisited',
    '重访 MoE 的算力最优扩展',
    'research',
  ],
]

/** Fillers: `[subreddit, flair, en, zh, category]` with `{m}` = a model name. */
export const REDDIT_FILLER: Array<[string, string, string, string, Category]> = [
  [
    'LocalLLaMA',
    'Discussion',
    'Is {m} actually better than its benchmarks suggest?',
    '{m} 的实际表现真的比跑分更好吗？',
    'discussion',
  ],
  [
    'LocalLLaMA',
    'Resources',
    '{m} GGUF quants are up — here is the perplexity table',
    '{m} 的 GGUF 量化已上传，附困惑度对比表',
    'tool',
  ],
  [
    'LocalLLaMA',
    'Question | Help',
    'Best settings for {m} on 24 GB VRAM?',
    '24GB 显存跑 {m} 的最佳参数是什么？',
    'discussion',
  ],
  [
    'MachineLearning',
    'Discussion',
    '[D] What is the real inference cost of {m}?',
    '[D] {m} 的真实推理成本是多少？',
    'discussion',
  ],
  ['singularity', 'AI', '{m} scores a new high on ARC-AGI-3', '{m} 在 ARC-AGI-3 上刷新纪录', 'industry'],
  [
    'OpenAI',
    'Discussion',
    'Switched my team from {m} this week — first impressions',
    '这周把团队从 {m} 切换过来了，谈谈初步感受',
    'discussion',
  ],
  [
    'ClaudeAI',
    'Productivity',
    'Using {m} for code review alongside Claude — a comparison',
    '把 {m} 和 Claude 一起用来做代码审查的对比',
    'engineering',
  ],
  [
    'LLMDevs',
    'Tools',
    'Structured outputs with {m}: what broke and how we fixed it',
    '用 {m} 做结构化输出：踩过的坑和解决办法',
    'engineering',
  ],
  [
    'artificial',
    'News',
    'Report: enterprise adoption of {m} doubled this quarter',
    '报告：{m} 的企业采用率本季度翻倍',
    'industry',
  ],
  [
    'GeminiAI',
    'Discussion',
    '{m} in the Gemini app vs AI Studio — why do answers differ?',
    'Gemini 应用里的 {m} 和 AI Studio 为什么回答不同？',
    'discussion',
  ],
  [
    'DeepSeek',
    'Discussion',
    'Running {m} through the DeepSeek-compatible API — latency notes',
    '通过兼容 DeepSeek 的 API 跑 {m}：延迟记录',
    'engineering',
  ],
  [
    'StableDiffusion',
    'Workflow Included',
    'Upscaling pipeline built around {m} captions',
    '围绕 {m} 生成标注搭建的放大工作流',
    'tool',
  ],
]

export const MODEL_NAMES = [
  'Qwen3-Max',
  'DeepSeek-V4',
  'GLM-5 Air',
  'Kimi K2.5',
  'GPT-5.5',
  'Gemini 3 Flash',
  'Claude Sonnet 5',
  'Mistral Medium 3',
  'MiniMax-M3',
  'Llama 5 8B',
]

/** `[handle, display name, org, text, zh, category, link?, day offset?]` — official lab accounts only. */
export type XSeed = [string, string, string, string, string, Category, string?, number?]

export const X_POSTS: XSeed[] = [
  [
    'deepseek_ai',
    'DeepSeek',
    'deepseek',
    'DeepSeek-V4 is live. Open weights, 1M context, MIT license. Tech report and weights below.',
    'DeepSeek-V4 正式上线：开放权重、百万上下文、MIT 许可。技术报告与权重见下。',
    'release',
    'lab:deepseek-v4',
    -3,
  ],
  [
    'AnthropicAI',
    'Anthropic',
    'anthropic',
    'Introducing Claude Opus 5: our most capable model for agentic coding and long-horizon research, with a 2M-token context window.',
    '推出 Claude Opus 5：我们在智能体编程和长程研究上能力最强的模型，上下文窗口达 200 万 token。',
    'release',
    'lab:claude-opus5',
    -1,
  ],
  [
    'claudeai',
    'Claude',
    'anthropic',
    'Claude can now keep working in the background while you do something else. Background agents are rolling out to Pro and Max today.',
    'Claude 现在可以在后台持续工作，你可以去做别的事。后台智能体今天起向 Pro 和 Max 用户推送。',
    'product',
    'lab:claude-bg',
  ],
  [
    'OpenAI',
    'OpenAI',
    'openai',
    'GPT-5.5 is rolling out to all ChatGPT users today, with stronger reasoning over long documents.',
    'GPT-5.5 今天起向所有 ChatGPT 用户推送，长文档推理能力更强。',
    'release',
    'lab:gpt55',
  ],
  [
    'OpenAIDevs',
    'OpenAI Developers',
    'openai',
    'Codex CLI 0.48: parallel sandboxes, resumable sessions and a new /review command.',
    'Codex CLI 0.48：并行沙箱、可恢复会话，以及新的 /review 命令。',
    'product',
    'gh:openai/codex',
  ],
  [
    'GoogleDeepMind',
    'Google DeepMind',
    'google',
    'Gemini 3 Ultra is here: state of the art on 18 of the 20 benchmarks we track, available in the Gemini API today.',
    'Gemini 3 Ultra 来了：在我们跟踪的 20 项基准中有 18 项达到最佳，今天起可在 Gemini API 中使用。',
    'release',
    'lab:gemini3-ultra',
  ],
  [
    'GoogleAIStudio',
    'Google AI Studio',
    'google',
    'You can now build with Gemini 3 Flash in AI Studio for free — 1M context, native audio in and out.',
    '现在可以在 AI Studio 免费使用 Gemini 3 Flash 构建应用：百万上下文，原生语音输入输出。',
    'product',
  ],
  [
    'GeminiApp',
    'Google Gemini',
    'google',
    'Deep Research in the Gemini app can now read your Drive files and cite them inline.',
    'Gemini 应用中的 Deep Research 现在可以读取你的云端硬盘文件，并在文中直接引用。',
    'product',
    'lab:gemini-drive',
  ],
  [
    'Alibaba_Qwen',
    'Qwen',
    'qwen',
    'Qwen3-Coder-Next: agentic coding with a 256K context, open weights on Hugging Face and ModelScope.',
    'Qwen3-Coder-Next：256K 上下文的智能体编程模型，权重已在 Hugging Face 和魔搭开放。',
    'release',
    'lab:qwen-coder-next',
    -1,
  ],
  [
    'Kimi_Moonshot',
    'Kimi.ai',
    'kimi',
    'Kimi K2.5 is open source: a 1T MoE with a 256K context, the strongest open model on SWE-bench Verified in our tests.',
    'Kimi K2.5 开源：1T 参数 MoE，256K 上下文，在我们的测试中是 SWE-bench Verified 上最强的开源模型。',
    'release',
    'lab:kimi-k25',
  ],
  [
    'Zai_org',
    'Z.ai',
    'zhipu',
    'GLM-5 Air is out: 106B MoE, 12B active, MIT license. Try it on z.ai or download it from Hugging Face.',
    'GLM-5 Air 发布：106B MoE，激活 12B，MIT 许可。可在 z.ai 体验或从 Hugging Face 下载。',
    'release',
    'lab:glm5-air',
  ],
  [
    'MistralAI',
    'Mistral AI',
    'mistral',
    'Magistral Medium 2 is now available in Le Chat and on La Plateforme.',
    'Magistral Medium 2 现已在 Le Chat 和 La Plateforme 上线。',
    'release',
    'lab:magistral2',
  ],
  [
    'AIatMeta',
    'AI at Meta',
    'meta',
    'We are releasing a family of Llama research models for on-device speech, with code and weights for researchers.',
    '我们发布了一组面向端侧语音的 Llama 研究模型，向研究者开放代码与权重。',
    'research',
    'lab:llama-speech',
  ],
  [
    'MiniMax_AI',
    'MiniMax',
    'minimax',
    'MiniMax-M3 is live: a 456B MoE with native agent tool use, open weights today.',
    'MiniMax-M3 上线：456B MoE，原生支持智能体工具调用，今天开放权重。',
    'release',
    'lab:minimax-m3',
  ],
  [
    'SpaceXAI',
    'xAI',
    'xai',
    'The Grok 5 API is now generally available with a 2M context window.',
    'Grok 5 API 现已全面开放，上下文窗口 200 万。',
    'release',
    'lab:grok5',
  ],
  [
    'grok',
    'Grok',
    'xai',
    'Grok can now search and summarise live X threads, with citations.',
    'Grok 现在可以搜索并总结 X 上的实时讨论串，并附上引用。',
    'product',
  ],
  [
    'OpenAI',
    'OpenAI',
    'openai',
    'Applications for the OpenAI Residency 2027 cohort are open.',
    'OpenAI Residency 2027 期开始接受申请。',
    'industry',
    'lab:residency',
  ],
  [
    'AnthropicAI',
    'Anthropic',
    'anthropic',
    'New interpretability research: tracing the circuits Claude uses to plan ahead when writing rhymes and code.',
    '新的可解释性研究：追踪 Claude 在写押韵诗和代码时提前规划所用的电路。',
    'research',
    'lab:claude-circuits',
  ],
  [
    'GoogleDeepMind',
    'Google DeepMind',
    'google',
    'AlphaProof 2 solves 5 of 6 problems from this year’s IMO shortlist, with every proof verified in Lean.',
    'AlphaProof 2 解出今年 IMO 候选题中的 5 道，所有证明均经 Lean 验证。',
    'research',
    'lab:alphaproof2',
  ],
  [
    'deepseek_ai',
    'DeepSeek',
    'deepseek',
    'Off-peak pricing: 50% off DeepSeek API calls between 16:30 and 00:30 UTC, starting today.',
    '夜间优惠：每天 UTC 16:30 至 00:30 调用 DeepSeek API 享五折，今天起生效。',
    'industry',
    'lab:deepseek-offpeak',
  ],
  [
    'Alibaba_Qwen',
    'Qwen',
    'qwen',
    'Qwen3-Max-Thinking is now in Qwen Chat. Try it on your hardest maths problems.',
    'Qwen3-Max-Thinking 已上线 Qwen Chat，拿你最难的数学题来试试。',
    'product',
    'lab:qwen-max-thinking',
  ],
  [
    'MistralAI',
    'Mistral AI',
    'mistral',
    'Devstral 2: our open coding model gets twice the context and better tool use.',
    'Devstral 2：我们的开源编程模型上下文翻倍，工具调用更强。',
    'release',
    'lab:devstral2',
  ],
  [
    'AIatMeta',
    'AI at Meta',
    'meta',
    'Our paper on scaling self-supervised video models is out, with code and checkpoints.',
    '我们关于扩展自监督视频模型的论文已发布，附代码与检查点。',
    'research',
    'lab:meta-video',
  ],
  [
    'OpenAIDevs',
    'OpenAI Developers',
    'openai',
    'Realtime API: new voices, lower latency and 30% cheaper audio output.',
    'Realtime API：新增音色、延迟更低，音频输出价格降低 30%。',
    'product',
    'lab:realtime',
  ],
]

/** X fillers per account: `[handle, name, org, en, zh, category]`, `{m}` = model. */
export const X_FILLER: Array<[string, string, string, string, string, Category]> = [
  [
    'OpenAIDevs',
    'OpenAI Developers',
    'openai',
    'Tip: {m} handles 400-page PDFs in a single call. Here is how to set it up.',
    '小技巧：{m} 一次调用就能处理 400 页 PDF，配置方法如下。',
    'engineering',
  ],
  [
    'GoogleAIStudio',
    'Google AI Studio',
    'google',
    'New in AI Studio: compare {m} side by side with your own prompts.',
    'AI Studio 新功能：用你自己的提示词并排对比 {m}。',
    'product',
  ],
  [
    'claudeai',
    'Claude',
    'anthropic',
    'A quick look at what people built with Claude this week, from spreadsheets to 3D games.',
    '看看大家这周用 Claude 做了什么：从电子表格到 3D 游戏。',
    'discussion',
  ],
  [
    'Alibaba_Qwen',
    'Qwen',
    'qwen',
    '{m} now supports 119 languages in Qwen Chat.',
    'Qwen Chat 中的 {m} 现已支持 119 种语言。',
    'product',
  ],
  [
    'deepseek_ai',
    'DeepSeek',
    'deepseek',
    'Scheduled maintenance for the DeepSeek API this weekend; the app is unaffected.',
    '本周末 DeepSeek API 例行维护，应用不受影响。',
    'industry',
  ],
  [
    'MistralAI',
    'Mistral AI',
    'mistral',
    'Le Chat now remembers your projects across conversations.',
    'Le Chat 现在可以跨对话记住你的项目。',
    'product',
  ],
  [
    'Kimi_Moonshot',
    'Kimi.ai',
    'kimi',
    'Kimi now reads up to 500 web pages per research task.',
    'Kimi 现在每个研究任务最多可阅读 500 个网页。',
    'product',
  ],
  [
    'GoogleDeepMind',
    'Google DeepMind',
    'google',
    'A thread on how we evaluate {m} for safety before launch.',
    '一条推文串：我们如何在发布前评估 {m} 的安全性。',
    'research',
  ],
]

export interface LabSeed {
  id: string
  company: string
  kind: LabKind
  surface: string
  precision: 'instant' | 'day' | 'month' | 'first-seen'
  title: string
  zh: string
  summary: string
  path: string
  /** Day offset from the end (-1 = last closed edition); spread otherwise. */
  day?: number
  flagship?: boolean
  link?: string
  alsoOn?: Array<{ url: string; surface: string }>
}

/** Company id → display name, config weight, and the host their posts live on. */
export const COMPANIES: Record<string, { name: string; weight: number; host: string; mode: string }> = {
  anthropic: { name: 'Anthropic', weight: 1.0, host: 'www.anthropic.com', mode: 'payload' },
  openai: { name: 'OpenAI', weight: 1.0, host: 'openai.com', mode: 'feed' },
  google: { name: 'Google', weight: 1.0, host: 'blog.google', mode: 'feed' },
  deepseek: { name: 'DeepSeek', weight: 1.0, host: 'api-docs.deepseek.com', mode: 'html' },
  xai: { name: 'xAI', weight: 1.0, host: 'x.ai', mode: 'jina' },
  zhipu: { name: 'Zhipu AI', weight: 0.9, host: 'www.zhipuai.cn', mode: 'json' },
  kimi: { name: 'Moonshot AI', weight: 0.9, host: 'www.kimi.ai', mode: 'payload' },
  qwen: { name: 'Qwen', weight: 0.9, host: 'qwen.ai', mode: 'json' },
  meta: { name: 'Meta AI', weight: 0.8, host: 'ai.meta.com', mode: 'html' },
  mistral: { name: 'Mistral AI', weight: 0.8, host: 'mistral.ai', mode: 'feed' },
  minimax: { name: 'MiniMax', weight: 0.8, host: 'www.minimax.io', mode: 'json' },
}

export const LAB_POSTS: LabSeed[] = [
  {
    id: 'claude-opus5',
    company: 'anthropic',
    kind: 'model',
    surface: 'news',
    precision: 'instant',
    day: -1,
    flagship: true,
    title: 'Introducing Claude Opus 5',
    zh: '推出 Claude Opus 5',
    summary:
      'Claude Opus 5 is our most capable model for agentic coding and long-horizon research. It sustains multi-day tasks, reads 2M tokens of context and sets a new state of the art on SWE-bench Verified.',
    path: '/news/claude-opus-5',
    alsoOn: [{ url: 'https://platform.claude.com/docs/en/release-notes/overview', surface: 'changelog' }],
  },
  {
    id: 'claude-bg',
    company: 'anthropic',
    kind: 'product',
    surface: 'news',
    precision: 'instant',
    day: -9,
    title: 'Claude Code background agents are now generally available',
    zh: 'Claude Code 后台智能体全面上线',
    summary: 'Background agents keep working on long tasks in a cloud sandbox and report back with a pull request.',
    path: '/news/claude-code-background-agents',
  },
  {
    id: 'claude-circuits',
    company: 'anthropic',
    kind: 'research',
    surface: 'research',
    precision: 'instant',
    day: -15,
    title: 'Tracing the planning circuits in Claude',
    zh: '追踪 Claude 的规划电路',
    summary: 'Using attribution graphs we find features that plan several tokens ahead, both in poetry and in code.',
    path: '/research/planning-circuits',
  },
  {
    id: 'claude-sandbox',
    company: 'anthropic',
    kind: 'engineering',
    surface: 'engineering',
    precision: 'day',
    day: -22,
    title: 'How we built the Claude Code sandbox',
    zh: '我们如何构建 Claude Code 沙箱',
    summary: 'Filesystem and network isolation for agents, and why we chose gVisor over microVMs.',
    path: '/engineering/claude-code-sandbox',
  },
  {
    id: 'files-api',
    company: 'anthropic',
    kind: 'product',
    surface: 'changelog',
    precision: 'day',
    day: -30,
    title: 'Claude Developer Platform: the Files API is generally available',
    zh: 'Claude 开发者平台：Files API 全面开放',
    summary: 'Upload once, reference files across requests; now with 500 MB per file.',
    path: '/docs/en/release-notes/overview#files-api-ga',
  },
  {
    id: 'gpt55',
    company: 'openai',
    kind: 'model',
    surface: 'news',
    precision: 'instant',
    day: -6,
    flagship: true,
    title: 'Introducing GPT-5.5',
    zh: '推出 GPT-5.5',
    summary:
      'GPT-5.5 improves reasoning over long documents and makes fewer tool-use mistakes; rolling out to all ChatGPT users and the API.',
    path: '/index/introducing-gpt-5-5',
  },
  {
    id: 'codex-parallel',
    company: 'openai',
    kind: 'product',
    surface: 'news',
    precision: 'instant',
    day: -12,
    title: 'Codex: parallel cloud tasks for Plus users',
    zh: 'Codex：为 Plus 用户开放并行云端任务',
    summary: 'Run up to five Codex tasks at once in isolated cloud sandboxes, each ending in a reviewable diff.',
    path: '/index/codex-parallel-tasks',
  },
  {
    id: 'realtime',
    company: 'openai',
    kind: 'product',
    surface: 'changelog',
    precision: 'day',
    day: -19,
    title: 'API changelog: Realtime API adds new voices and cheaper audio output',
    zh: 'API 更新：Realtime API 新增音色并下调音频输出价格',
    summary: 'Eight new voices, lower latency and audio output priced 30% lower.',
    path: '/api/docs/changelog',
  },
  {
    id: 'residency',
    company: 'openai',
    kind: 'company',
    surface: 'news',
    precision: 'instant',
    day: -26,
    title: 'OpenAI Residency 2027: applications open',
    zh: 'OpenAI Residency 2027 开放申请',
    summary: 'A six-month programme for researchers and engineers coming from other fields.',
    path: '/index/openai-residency-2027',
  },
  {
    id: 'gemini3-ultra',
    company: 'google',
    kind: 'model',
    surface: 'blog',
    precision: 'instant',
    day: -8,
    flagship: true,
    title: 'Gemini 3 Ultra: our most capable model yet',
    zh: 'Gemini 3 Ultra：迄今最强的 Gemini',
    summary:
      'State of the art on 18 of 20 benchmarks, with native tool use and a 2M context; available in the Gemini API and the Gemini app.',
    path: '/technology/google-deepmind/gemini-3-ultra/',
  },
  {
    id: 'gemini-flash',
    company: 'google',
    kind: 'product',
    surface: 'changelog',
    precision: 'day',
    day: -2,
    title: 'Gemini API: Gemini 3 Flash is now stable',
    zh: 'Gemini API：Gemini 3 Flash 转为稳定版',
    summary: 'gemini-3-flash is stable; the preview alias will be retired in two weeks.',
    path: '/gemini-api/docs/changelog',
  },
  {
    id: 'alphaproof2',
    company: 'google',
    kind: 'research',
    surface: 'research',
    precision: 'instant',
    day: -17,
    title: 'AlphaProof 2 and the road to formal mathematics',
    zh: 'AlphaProof 2 与通往形式化数学之路',
    summary: 'Our system solved five of six IMO shortlist problems with proofs checked in Lean.',
    path: '/discover/blog/alphaproof-2/',
  },
  {
    id: 'gemini-drive',
    company: 'google',
    kind: 'product',
    surface: 'blog',
    precision: 'instant',
    day: -11,
    title: 'Deep Research in the Gemini app can now use your Drive',
    zh: 'Gemini 应用的 Deep Research 现在可以使用你的云端硬盘',
    summary: 'Point Deep Research at folders in Drive and get reports that cite your own documents.',
    path: '/products/gemini/deep-research-drive/',
  },
  {
    id: 'deepseek-v4',
    company: 'deepseek',
    kind: 'model',
    surface: 'news',
    precision: 'day',
    day: -3,
    flagship: true,
    title: 'DeepSeek-V4 Release',
    zh: 'DeepSeek-V4 发布',
    summary:
      'DeepSeek-V4 is open-sourced under MIT: a mixture-of-experts model with a 1M-token context, available in the app, the API and on Hugging Face.',
    path: '/news/news260916',
    link: 'gh:deepseek-ai/deepseek-v4',
    alsoOn: [{ url: 'https://huggingface.co/deepseek-ai/DeepSeek-V4', surface: 'huggingface' }],
  },
  {
    id: 'deepseek-offpeak',
    company: 'deepseek',
    kind: 'company',
    surface: 'updates',
    precision: 'day',
    day: -14,
    title: 'Off-peak pricing for the DeepSeek API',
    zh: 'DeepSeek API 推出错峰优惠',
    summary: '50% off between 16:30 and 00:30 UTC for all models.',
    path: '/updates',
  },
  {
    id: 'deepep',
    company: 'deepseek',
    kind: 'engineering',
    surface: 'github',
    precision: 'instant',
    day: -24,
    title: 'deepseek-ai/DeepEP v2: expert-parallel kernels for V4',
    zh: 'deepseek-ai/DeepEP v2：面向 V4 的专家并行内核',
    summary: 'Low-latency all-to-all kernels for MoE training and inference.',
    path: '',
  },
  {
    id: 'grok5',
    company: 'xai',
    kind: 'model',
    surface: 'news',
    precision: 'day',
    day: -5,
    flagship: true,
    title: 'Grok 5 API is generally available',
    zh: 'Grok 5 API 全面开放',
    summary: 'Grok 5 is available to all developers with a 2M-token context window and live search.',
    path: '/news/grok-5-api',
  },
  {
    id: 'xai-search',
    company: 'xai',
    kind: 'product',
    surface: 'docs',
    precision: 'first-seen',
    day: -20,
    title: 'Release notes: live search in the xAI API',
    zh: '更新说明：xAI API 支持实时搜索',
    summary: 'Search X and the web from the API with citations.',
    path: '/developers/release-notes',
  },
  {
    id: 'glm5-air',
    company: 'zhipu',
    kind: 'model',
    surface: 'news',
    precision: 'instant',
    day: -10,
    title: 'GLM-5 Air: an efficient open MoE',
    zh: 'GLM-5 Air：高效的开源 MoE 模型',
    summary: '106B total and 12B active parameters, MIT-licensed, with strong tool calling.',
    path: '/zh/news/186',
  },
  {
    id: 'glm-fc',
    company: 'zhipu',
    kind: 'product',
    surface: 'docs',
    precision: 'day',
    day: -4,
    title: 'Z.ai API: GLM-5 Air function calling and context caching',
    zh: 'Z.ai API：GLM-5 Air 支持函数调用与上下文缓存',
    summary: 'Parallel function calls and cached context priced at a fifth of input tokens.',
    path: '/release-notes/new-released',
  },
  {
    id: 'kimi-k25',
    company: 'kimi',
    kind: 'model',
    surface: 'blog',
    precision: 'day',
    day: -7,
    flagship: true,
    title: 'Kimi K2.5: open agentic intelligence',
    zh: 'Kimi K2.5：开放的智能体智能',
    summary: 'A 1T-parameter MoE with a 256K context and open weights, tuned for long agentic tasks.',
    path: '/blog/kimi-k2-5',
  },
  {
    id: 'kimi-cache',
    company: 'kimi',
    kind: 'product',
    surface: 'changelog',
    precision: 'month',
    day: -21,
    title: 'Platform changelog: context caching price cut',
    zh: '平台更新：上下文缓存降价',
    summary: 'Cached tokens now cost 75% less.',
    path: '/docs/platform-changelog',
  },
  {
    id: 'qwen-coder-next',
    company: 'qwen',
    kind: 'model',
    surface: 'blog',
    precision: 'instant',
    day: -1,
    title: 'Qwen3-Coder-Next: agentic coding in the open',
    zh: 'Qwen3-Coder-Next：开放的智能体编程模型',
    summary:
      'Open weights, a 256K context and state-of-the-art results among open models on SWE-bench and Terminal-Bench.',
    path: '/blog?id=qwen3-coder-next',
    link: 'gh:qwenlm/qwen3-coder',
    alsoOn: [{ url: 'https://huggingface.co/Qwen/Qwen3-Coder-Next', surface: 'huggingface' }],
  },
  {
    id: 'qwen-max-thinking',
    company: 'qwen',
    kind: 'model',
    surface: 'huggingface',
    precision: 'instant',
    day: -13,
    title: 'Qwen/Qwen3-Max-Thinking',
    zh: 'Qwen/Qwen3-Max-Thinking',
    summary: 'New model repository on Hugging Face.',
    path: '',
  },
  {
    id: 'llama-speech',
    company: 'meta',
    kind: 'research',
    surface: 'blog',
    precision: 'day',
    day: -16,
    title: 'Llama speech research models for on-device use',
    zh: '面向端侧的 Llama 语音研究模型',
    summary: 'Small speech-native models released to researchers with code and weights.',
    path: '/blog/llama-speech-research/',
  },
  {
    id: 'meta-video',
    company: 'meta',
    kind: 'research',
    surface: 'blog',
    precision: 'day',
    day: -27,
    title: 'Scaling self-supervised video models',
    zh: '扩展自监督视频模型',
    summary: 'What changes when video world models are trained on ten times more data.',
    path: '/blog/scaling-video-ssl/',
  },
  {
    id: 'magistral2',
    company: 'mistral',
    kind: 'model',
    surface: 'news',
    precision: 'instant',
    day: -18,
    title: 'Magistral Medium 2',
    zh: 'Magistral Medium 2',
    summary: 'Our reasoning model gets faster, multilingual and cheaper; available in Le Chat and La Plateforme.',
    path: '/news/magistral-medium-2',
  },
  {
    id: 'devstral2',
    company: 'mistral',
    kind: 'model',
    surface: 'news',
    precision: 'instant',
    day: -2,
    title: 'Devstral 2: the open coding model, upgraded',
    zh: 'Devstral 2：开源编程模型全面升级',
    summary: 'Twice the context and better tool use, Apache-2.0.',
    path: '/news/devstral-2',
  },
  {
    id: 'mistral-nvidia',
    company: 'mistral',
    kind: 'company',
    surface: 'news',
    precision: 'instant',
    day: -23,
    title: 'Mistral and NVIDIA partner on sovereign AI compute in France',
    zh: 'Mistral 与英伟达合作在法国建设主权 AI 算力',
    summary: 'An 18,000-GPU cluster near Paris for European customers.',
    path: '/news/mistral-nvidia-compute',
  },
  {
    id: 'minimax-m3',
    company: 'minimax',
    kind: 'model',
    surface: 'news',
    precision: 'instant',
    day: -25,
    flagship: true,
    title: 'MiniMax-M3: native agents, open weights',
    zh: 'MiniMax-M3：原生智能体，开放权重',
    summary: 'A 456B MoE trained for tool use end to end, with a 1M context.',
    path: '/news/minimax-m3',
  },
  {
    id: 'minimax-notes',
    company: 'minimax',
    kind: 'product',
    surface: 'docs',
    precision: 'month',
    day: -2,
    title: 'Release notes: M3 function calling and 1M context in the API',
    zh: '更新说明：API 中的 M3 函数调用与百万上下文',
    summary: 'Function calling, JSON mode and the full context window are now in the API.',
    path: '/docs/release-notes/models',
  },
]

/** Changelog / release filler per company: `[company, kind, surface, en, zh]`; `{v}` = a counter. */
export const LAB_FILLER: Array<[string, LabKind, string, string, string]> = [
  ['anthropic', 'product', 'releases', 'anthropics/claude-code v2.{v}.0', 'anthropics/claude-code v2.{v}.0'],
  ['openai', 'product', 'releases', 'openai/codex rust-v0.{v}.0', 'openai/codex rust-v0.{v}.0'],
  [
    'google',
    'product',
    'changelog',
    'Gemini API changelog: batch mode for gemini-3-flash (update {v})',
    'Gemini API 更新：gemini-3-flash 批处理模式（第 {v} 次更新）',
  ],
  [
    'deepseek',
    'product',
    'updates',
    'DeepSeek API update: JSON output improvements ({v})',
    'DeepSeek API 更新：JSON 输出改进（{v}）',
  ],
  ['qwen', 'model', 'huggingface', 'Qwen/Qwen3-{v}B-Instruct-2609', 'Qwen/Qwen3-{v}B-Instruct-2609'],
  [
    'mistral',
    'product',
    'changelog',
    'Docs changelog: La Plateforme API update {v}',
    '文档更新：La Plateforme API 第 {v} 次更新',
  ],
  [
    'zhipu',
    'product',
    'docs',
    'Z.ai release notes: GLM-5 tool-calling fixes ({v})',
    'Z.ai 更新说明：GLM-5 工具调用修复（{v}）',
  ],
  [
    'meta',
    'engineering',
    'github',
    'facebookresearch: new repository for efficient attention kernels ({v})',
    'facebookresearch：高效注意力内核新仓库（{v}）',
  ],
  [
    'minimax',
    'product',
    'docs',
    'MiniMax platform: rate-limit changes for M3 ({v})',
    'MiniMax 平台：M3 的限流调整（{v}）',
  ],
  ['kimi', 'product', 'changelog', 'Kimi platform: new file-upload limits ({v})', 'Kimi 平台：文件上传限制调整（{v}）'],
]
