/**
 * Seed text for the mock API: hand-written anchors plus phrase pools the generator combines.
 * Everything here is fictional sample data for local development; none of it is published.
 */
import { BOARDS, type BoardMeta, type SignalMeta } from '@resonance/schema'

/** `[owner/name, language, license, base stars, peak stars/day, description, zh blurb, topics]` */
export type RepoSeed = [string, string, string, number, number, string, string, string[]]

export const REPOS: RepoSeed[] = [
  [
    'resonant-labs/echo-attn',
    'Cuda',
    'Apache-2.0',
    2100,
    1500,
    'Echo Attention: exact softmax attention in linear time. Drop-in CUDA and Triton kernels for PyTorch.',
    '线性时间的精确 softmax 注意力，提供可直接替换的 CUDA 与 Triton 内核。',
    ['attention', 'cuda', 'llm', 'inference'],
  ],
  [
    'deepseek-ai/DeepSeek-V4',
    'Python',
    'MIT',
    18400,
    1600,
    'DeepSeek-V4: open-weights mixture-of-experts model with a 1M-token context window.',
    'DeepSeek-V4：开放权重的 MoE 大模型，支持百万 token 上下文。',
    ['llm', 'moe', 'open-weights'],
  ],
  [
    'karpathy/nanochat',
    'Python',
    'MIT',
    31200,
    1300,
    'The best ChatGPT that $100 can buy: a full-stack LLM training and chat pipeline in one small repo.',
    '一百美元能买到的最好的 ChatGPT：一个小仓库跑通训练到对话的全流程。',
    ['llm', 'education', 'training'],
  ],
  [
    'modelcontextprotocol/servers',
    'TypeScript',
    'MIT',
    68900,
    700,
    'Reference implementations of Model Context Protocol servers.',
    'MCP（模型上下文协议）服务器的官方参考实现合集。',
    ['mcp', 'agents', 'tools'],
  ],
  [
    'vllm-project/vllm',
    'Python',
    'Apache-2.0',
    58300,
    650,
    'A high-throughput and memory-efficient inference and serving engine for LLMs.',
    '高吞吐、省显存的大模型推理与服务引擎。',
    ['inference', 'llm', 'serving'],
  ],
  [
    'ollama/ollama',
    'Go',
    'MIT',
    151000,
    600,
    'Get up and running with large language models locally.',
    '在本地一条命令跑起大语言模型。',
    ['llm', 'local', 'inference'],
  ],
  [
    'ggml-org/llama.cpp',
    'C++',
    'MIT',
    86400,
    520,
    'LLM inference in C/C++ with minimal setup and state-of-the-art performance on a wide range of hardware.',
    '纯 C/C++ 的大模型推理，几乎零依赖，覆盖各类硬件。',
    ['inference', 'llm', 'quantization'],
  ],
  [
    'langchain-ai/langgraph',
    'Python',
    'MIT',
    19800,
    480,
    'Build resilient language agents as graphs.',
    '用图的方式构建可靠、可恢复的语言智能体。',
    ['agents', 'llm', 'orchestration'],
  ],
  [
    'browser-use/browser-use',
    'Python',
    'MIT',
    71200,
    900,
    'Make websites accessible for AI agents. Automate tasks online with ease.',
    '让网站对 AI 智能体可用，轻松自动化线上任务。',
    ['agents', 'browser', 'automation'],
  ],
  [
    'unslothai/unsloth',
    'Python',
    'Apache-2.0',
    45100,
    560,
    'Fine-tune and run reasoning LLMs 2x faster with 70% less VRAM.',
    '微调与运行推理模型：速度翻倍，显存省七成。',
    ['fine-tuning', 'llm', 'lora'],
  ],
  [
    'huggingface/smolagents',
    'Python',
    'Apache-2.0',
    22700,
    420,
    'A barebones library for agents that think in code.',
    '一个极简的智能体库：让智能体用代码思考。',
    ['agents', 'llm'],
  ],
  [
    'sgl-project/sglang',
    'Python',
    'Apache-2.0',
    17900,
    450,
    'SGLang is a fast serving framework for large language models and vision language models.',
    '面向大语言模型与视觉语言模型的高速服务框架。',
    ['inference', 'serving', 'llm'],
  ],
  [
    'infiniflow/ragflow',
    'Python',
    'Apache-2.0',
    64800,
    540,
    'An open-source RAG engine based on deep document understanding.',
    '基于深度文档理解的开源 RAG 引擎。',
    ['rag', 'llm', 'documents'],
  ],
  [
    'mem0ai/mem0',
    'Python',
    'Apache-2.0',
    39500,
    610,
    'Universal memory layer for AI agents.',
    '为 AI 智能体准备的通用记忆层。',
    ['agents', 'memory', 'llm'],
  ],
  [
    'comfyanonymous/ComfyUI',
    'Python',
    'GPL-3.0',
    89700,
    470,
    'The most powerful and modular diffusion model GUI, API and backend with a graph interface.',
    '最强大的模块化扩散模型界面：节点式工作流、API 与后端。',
    ['diffusion', 'image-generation'],
  ],
  [
    'QwenLM/Qwen3-Coder',
    'Python',
    'Apache-2.0',
    12600,
    820,
    'Qwen3-Coder is the code version of Qwen3, the large language model series developed by the Qwen team.',
    'Qwen3 的代码特化版本，面向智能体式编程。',
    ['llm', 'code', 'open-weights'],
  ],
  [
    'google-gemini/gemini-cli',
    'TypeScript',
    'Apache-2.0',
    77300,
    750,
    'An open-source AI agent that brings the power of Gemini directly into your terminal.',
    '把 Gemini 直接带进终端的开源 AI 智能体。',
    ['agents', 'cli', 'llm'],
  ],
  [
    'openai/codex',
    'Rust',
    'Apache-2.0',
    43800,
    880,
    'Lightweight coding agent that runs in your terminal.',
    '在终端里运行的轻量级编程智能体。',
    ['agents', 'cli', 'code'],
  ],
  [
    'crewAIInc/crewAI',
    'Python',
    'MIT',
    38200,
    380,
    'Framework for orchestrating role-playing, autonomous AI agents.',
    '编排角色分工、自主协作的多智能体框架。',
    ['agents', 'multi-agent'],
  ],
  [
    'block/goose',
    'Rust',
    'Apache-2.0',
    20400,
    520,
    'An open-source, extensible AI agent that goes beyond code suggestions.',
    '开源可扩展的 AI 智能体：不止于代码补全，能装、能跑、能改、能测。',
    ['agents', 'mcp', 'cli'],
  ],
  [
    'mlc-ai/web-llm',
    'TypeScript',
    'Apache-2.0',
    16300,
    360,
    'High-performance in-browser LLM inference engine.',
    '浏览器内的高性能大模型推理引擎。',
    ['inference', 'webgpu', 'llm'],
  ],
  [
    'huggingface/lerobot',
    'Python',
    'Apache-2.0',
    17200,
    640,
    'Making AI for robotics more accessible with end-to-end learning.',
    '用端到端学习降低机器人 AI 的门槛。',
    ['robotics', 'imitation-learning'],
  ],
  [
    'exo-explore/exo',
    'Python',
    'GPL-3.0',
    29900,
    430,
    'Run your own AI cluster at home with everyday devices.',
    '用家里的日常设备拼出自己的 AI 集群。',
    ['inference', 'distributed', 'local'],
  ],
  [
    'letta-ai/letta',
    'Python',
    'Apache-2.0',
    18600,
    340,
    'The stateful agents framework with memory, reasoning and context management.',
    '有状态智能体框架：自带记忆、推理与上下文管理。',
    ['agents', 'memory'],
  ],
  [
    'tinygrad/tinygrad',
    'Python',
    'MIT',
    29400,
    300,
    'You like pytorch? You like micrograd? You love tinygrad!',
    '喜欢 PyTorch 和 micrograd？那你会爱上 tinygrad。',
    ['deep-learning', 'compiler'],
  ],
  [
    'lightpanda-io/browser',
    'Zig',
    'AGPL-3.0',
    12100,
    700,
    'The headless browser designed for AI and automation.',
    '为 AI 与自动化而生的无头浏览器。',
    ['browser', 'agents', 'automation'],
  ],
  [
    'microsoft/markitdown',
    'Python',
    'MIT',
    72600,
    560,
    'Python tool for converting files and office documents to Markdown.',
    '把各类文件与 Office 文档转成 Markdown 的 Python 工具。',
    ['rag', 'documents', 'llm'],
  ],
  [
    'stanfordnlp/dspy',
    'Python',
    'MIT',
    27500,
    330,
    'The framework for programming, not prompting, language models.',
    '对语言模型“编程”而不是“写提示词”的框架。',
    ['llm', 'prompting', 'optimization'],
  ],
  [
    'a-very-long-organization-name/an-extremely-long-repository-name-for-layout-testing',
    'Jupyter Notebook',
    'NOASSERTION',
    640,
    260,
    'A deliberately long description used to verify that cards clamp gracefully: retrieval-augmented, multi-agent, multimodal, long-context, tool-using, self-verifying everything.',
    '这是一段刻意写得很长的中文描述，用来验证卡片在窄屏上能否优雅地截断：检索增强、多智能体、多模态、长上下文、工具调用、自我验证，应有尽有。',
    ['rag', 'agents', 'multimodal'],
  ],
  [
    'anthropics/claude-cookbooks',
    'Jupyter Notebook',
    'MIT',
    24100,
    310,
    'A collection of notebooks and recipes showcasing effective ways of building with Claude.',
    '一组笔记本与配方，展示用 Claude 构建应用的有效方法。',
    ['llm', 'examples', 'agents'],
  ],
]

/** `[title, zh title, abstract, zh blurb, code repo (owner/name) | '', categories, source: hf|arxiv|journal]` */
export type PaperSeed = [string, string, string, string, string, string[], 'hf' | 'arxiv' | 'journal']

export const PAPERS: PaperSeed[] = [
  [
    'Echo Attention: Exact Softmax Attention in Linear Time via Resonant State Caching',
    'Echo Attention：借助共振状态缓存实现线性时间的精确 Softmax 注意力',
    'We show that exact softmax attention admits a linear-time evaluation when intermediate states are cached along a resonant basis. Echo Attention matches full attention bit-for-bit on sequences up to 4M tokens while reducing prefill latency by 6.2x on a single H100. We release CUDA and Triton kernels.',
    '证明精确 softmax 注意力可在线性时间内计算：4M token 序列上与全注意力逐位一致，单卡 H100 预填充延迟降低 6.2 倍，并开源内核。',
    'resonant-labs/echo-attn',
    ['cs.LG', 'cs.CL'],
    'hf',
  ],
  [
    'DeepSeek-V4 Technical Report',
    'DeepSeek-V4 技术报告',
    'We present DeepSeek-V4, a mixture-of-experts language model with 1M-token context. We describe the architecture, the training recipe, and a reinforcement-learning stage with verifiable rewards, and report results across reasoning, coding and agentic benchmarks.',
    'DeepSeek-V4 技术报告：百万上下文 MoE 架构、训练配方与可验证奖励的强化学习阶段，覆盖推理、代码与智能体评测。',
    'deepseek-ai/DeepSeek-V4',
    ['cs.CL', 'cs.AI'],
    'hf',
  ],
  [
    'MCP-Bench: Evaluating Tool-Using LLMs over the Model Context Protocol',
    'MCP-Bench：在模型上下文协议上评测会用工具的大模型',
    'We introduce MCP-Bench, 1,240 tasks spanning 86 real MCP servers. Frontier models solve 61% of single-server tasks but only 23% of tasks that require composing three or more servers.',
    '提出 MCP-Bench：86 个真实 MCP 服务器上的 1240 个任务。前沿模型单服务器任务通过率 61%，需要组合三个以上服务器时仅 23%。',
    'modelcontextprotocol/servers',
    ['cs.AI', 'cs.SE'],
    'hf',
  ],
  [
    'The Illusion of Agentic Progress: Contamination in Web-Browsing Benchmarks',
    '智能体进步的幻觉：网页浏览基准中的数据污染',
    'We audit five popular web-agent benchmarks and find that 38% of tasks can be solved from memorised answers without browsing. After decontamination, the gap between open and closed agents shrinks from 21 to 6 points.',
    '审计五个主流网页智能体基准：38% 的任务不用浏览、靠记忆即可作答；去污染后开源与闭源智能体差距从 21 分缩小到 6 分。',
    '',
    ['cs.AI', 'cs.CL'],
    'hf',
  ],
  [
    'Agents That Remember: A Benchmark for Long-Horizon Memory in LLM Agents',
    '会记忆的智能体：大模型智能体长程记忆基准',
    'Long-running agents must recall facts across sessions. We propose a benchmark of 900 multi-session tasks and show that retrieval-based memory layers outperform long-context prompting at one tenth of the cost.',
    '提出含 900 个跨会话任务的长程记忆基准，结果显示基于检索的记忆层以十分之一成本优于长上下文提示。',
    'mem0ai/mem0',
    ['cs.AI'],
    'hf',
  ],
  [
    'Speculative Decoding at Scale: Lessons from Serving a Trillion Tokens a Day',
    '大规模推测解码：日均万亿 token 服务的经验',
    'We report on deploying speculative decoding in a production serving stack, covering draft-model selection, acceptance-rate drift and scheduler interactions. We observe a 2.3x median latency reduction.',
    '分享在生产推理栈中部署推测解码的经验：草稿模型选择、接受率漂移与调度器交互，延迟中位数降低 2.3 倍。',
    'vllm-project/vllm',
    ['cs.LG', 'cs.DC'],
    'hf',
  ],
  [
    'RoboDreamer-2: World Models for Zero-Shot Manipulation',
    'RoboDreamer-2：用于零样本操作的世界模型',
    'A video world model trained on 40k hours of egocentric data enables zero-shot manipulation planning. RoboDreamer-2 improves success on unseen household tasks from 31% to 58%.',
    '在 4 万小时第一视角视频上训练世界模型，实现零样本操作规划，未见过的家务任务成功率从 31% 提升到 58%。',
    'huggingface/lerobot',
    ['cs.RO', 'cs.CV'],
    'hf',
  ],
  [
    'Small Models, Big Context: Distilling 1M-Token Reasoning into 3B Parameters',
    '小模型，大上下文：把百万 token 推理蒸馏进 30 亿参数',
    'We distil long-context reasoning traces into a 3B model with a curriculum over context length, retaining 91% of teacher accuracy on needle-style and multi-hop tasks.',
    '通过按上下文长度递进的课程蒸馏，让 3B 模型在大海捞针与多跳任务上保留教师模型 91% 的准确率。',
    '',
    ['cs.CL'],
    'hf',
  ],
  [
    'Do Coding Agents Actually Read the Docs? An Empirical Study of Tool Use in Terminal Agents',
    '编程智能体真的会读文档吗？终端智能体工具使用的实证研究',
    'Across 12k agent trajectories we find that agents open documentation in only 9% of failures that documentation would have prevented.',
    '分析 1.2 万条智能体轨迹：在本可靠文档避免的失败中，智能体只有 9% 的情况会去翻文档。',
    '',
    ['cs.SE', 'cs.AI'],
    'hf',
  ],
  [
    'Self-Verifying Chains: Reinforcement Learning with Process Rewards from Formal Proofs',
    '自验证推理链：用形式化证明提供过程奖励的强化学习',
    'We use a proof assistant as a dense process-reward signal and train a 32B model that closes 47% of miniF2F-hard.',
    '用证明助手提供稠密的过程奖励，训练出的 32B 模型可解决 miniF2F-hard 中 47% 的题目。',
    '',
    ['cs.LG', 'cs.LO'],
    'hf',
  ],
  [
    'Quantisation Without Tears: 3-Bit Weights with Learned Rotations',
    '无痛量化：借助可学习旋转的 3 比特权重',
    'Learned orthogonal rotations remove activation outliers before quantisation, giving near-lossless 3-bit weights for models up to 70B.',
    '量化前用可学习的正交旋转消除激活离群值，使 70B 以内模型的 3 比特权重几乎无损。',
    'ggml-org/llama.cpp',
    ['cs.LG'],
    'hf',
  ],
  [
    'A Foundation Model for Single-Cell Perturbation Response',
    '单细胞扰动响应的基础模型',
    'A transformer pretrained on 120M single-cell profiles predicts transcriptional responses to unseen genetic perturbations.',
    '在 1.2 亿单细胞图谱上预训练的 Transformer，可预测未见基因扰动下的转录响应。',
    '',
    ['q-bio.GN', 'cs.LG'],
    'journal',
  ],
]

/** Filler paper titles: `prefix + topic`, both with natural zh renderings. */
export const PAPER_PREFIX: Array<[string, string]> = [
  ['Rethinking ', '重新思考'],
  ['Scaling ', '规模化'],
  ['Towards Reliable ', '迈向可靠的'],
  ['A Closer Look at ', '深入审视'],
  ['Understanding ', '理解'],
  ['Revisiting ', '重访'],
  ['Efficient ', '高效的'],
  ['Beyond Benchmarks: ', '超越基准：'],
]

export const PAPER_TOPIC: Array<[string, string]> = [
  ['Test-Time Compute for Multimodal Reasoning', '多模态推理中的测试时计算'],
  ['Mixture-of-Experts Routing under Distribution Shift', '分布偏移下的专家混合路由'],
  ['Long-Context Retrieval in Code Language Models', '代码语言模型中的长上下文检索'],
  ['Reward Hacking in RLHF Pipelines', 'RLHF 流程中的奖励投机'],
  ['Speculative Decoding for Diffusion Language Models', '扩散语言模型的推测解码'],
  ['Tool-Augmented Agents for Scientific Discovery', '用于科学发现的工具增强智能体'],
  ['KV-Cache Compression at One Million Tokens', '百万 token 下的 KV 缓存压缩'],
  ['Synthetic Data for Low-Resource Translation', '低资源翻译中的合成数据'],
  ['Video Generation with Physical Consistency', '具备物理一致性的视频生成'],
  ['Multi-Agent Debate for Factuality', '用于提升事实性的多智能体辩论'],
  ['Preference Optimisation without Reference Models', '无参考模型的偏好优化'],
  ['Sparse Autoencoders for Mechanistic Interpretability', '用于机制可解释性的稀疏自编码器'],
  ['Speech-Native Language Models', '原生语音语言模型'],
  ['GUI Agents on Mobile Devices', '移动设备上的 GUI 智能体'],
  ['Retrieval-Augmented Generation over Tables and Charts', '面向表格与图表的检索增强生成'],
  ['Continual Pretraining of Open-Weights Models', '开放权重模型的持续预训练'],
]

export const PAPER_FINDING: Array<[string, string]> = [
  [
    'Shows consistent gains on reasoning and coding benchmarks at a fraction of the compute.',
    '以一小部分算力在推理与代码基准上取得稳定提升。',
  ],
  [
    'Identifies a failure mode that current evaluations miss, and proposes a simple fix.',
    '指出现有评测遗漏的一种失效模式，并给出简单的修复办法。',
  ],
  ['Releases a 40B-token dataset and strong open baselines.', '开源 400 亿 token 的数据集与强力基线。'],
  [
    'Finds that gains reported in prior work largely vanish under matched budgets.',
    '发现在同等预算下，先前工作报告的收益大多消失。',
  ],
  ['Introduces a training-free method that works across model families.', '提出一种无需训练、跨模型家族通用的方法。'],
  [
    'Provides scaling laws that predict performance within 2% across three orders of magnitude.',
    '给出的扩展定律在三个数量级内将性能预测误差控制在 2% 以内。',
  ],
]

export const AUTHORS = [
  'Yilun Chen',
  'Maya Okafor',
  'Jonas Richter',
  'Wei Zhang',
  'Priya Natarajan',
  'Tomás Ferreira',
  'Hannah Lindqvist',
  'Kenji Watanabe',
  'Lin Qiao',
  'Amara Diallo',
  'Noah Feldman',
  'Xinyu Liu',
  'Sofia Marchetti',
  'Rahul Mehta',
  'Zhou Ming',
  'Elena Petrova',
]
export const ORGS = [
  'Tsinghua University',
  'Stanford University',
  'ETH Zürich',
  'Shanghai AI Lab',
  'MIT CSAIL',
  'Hugging Face',
  'University of Toronto',
  'Peking University',
  'Allen Institute for AI',
  'KAIST',
]

/** Hand-written HN stories: `[title, zh title, url, zh blurb, linked entity ('gh:…' | 'arxiv:#<paper index>') | '']` */
export type NewsSeed = [string, string, string, string, string]

export const NEWS_ANCHORS: NewsSeed[] = [
  [
    'Echo Attention: exact softmax attention in linear time',
    'Echo Attention：线性时间的精确 softmax 注意力',
    'https://arxiv.org/abs/{{arxiv:0}}',
    '一篇声称“精确且线性”的注意力论文冲上 HN 首页，评论区在争论缓存开销与实际加速比。',
    'arxiv:#0',
  ],
  [
    'DeepSeek-V4 released with open weights',
    'DeepSeek-V4 开放权重发布',
    'https://github.com/deepseek-ai/DeepSeek-V4',
    'DeepSeek-V4 权重开放下载，讨论集中在百万上下文的实际可用性与推理成本。',
    'gh:deepseek-ai/deepseek-v4',
  ],
  [
    'Nanochat: The best ChatGPT that $100 can buy',
    'nanochat：一百美元能买到的最好的 ChatGPT',
    'https://github.com/karpathy/nanochat',
    'Karpathy 的新仓库：四小时、一百美元，从分词器到聊天界面完整训练一个小模型。',
    'gh:karpathy/nanochat',
  ],
  [
    'The illusion of agentic progress: contamination in web-browsing benchmarks',
    '智能体进步的幻觉：网页浏览基准的数据污染',
    'https://arxiv.org/abs/{{arxiv:3}}',
    '论文指出多数网页智能体基准可以“背答案”通过，HN 上对评测可信度的讨论很热烈。',
    'arxiv:#3',
  ],
  [
    'Lightpanda: a headless browser built for AI agents, written in Zig',
    'Lightpanda：用 Zig 写的、为 AI 智能体打造的无头浏览器',
    'https://github.com/lightpanda-io/browser',
    '主打比 Chrome 无头模式快一个数量级、内存占用小得多，适合大规模跑智能体。',
    'gh:lightpanda-io/browser',
  ],
  [
    'Show HN: I built a local-first RAG over 20 years of my email',
    'Show HN：我给自己二十年的邮件做了一个本地优先的 RAG',
    'https://blog.example.dev/local-first-email-rag',
    '作者分享了完全离线的邮件检索问答方案：SQLite 向量扩展加一个 3B 小模型。',
    '',
  ],
  [
    'What I learned running coding agents in production for a year',
    '在生产环境跑了一年编程智能体，我学到了什么',
    'https://engineering.example.com/a-year-of-agents',
    '一线团队的复盘：评测要先行、上下文要节制、人要留在回路里。',
    '',
  ],
  [
    'Why your RAG pipeline is slow (and it is not the vector database)',
    '你的 RAG 为什么慢（问题不在向量数据库）',
    'https://blog.example.dev/rag-latency',
    '逐段剖析 RAG 延迟：大头在重排与提示拼接，而不是向量检索。',
    '',
  ],
  [
    'Ask HN: Are you actually using MCP servers at work?',
    'Ask HN：你们工作中真的在用 MCP 服务器吗？',
    '',
    '一个关于 MCP 真实落地情况的提问帖，回答里既有成功案例也有安全顾虑。',
    'gh:modelcontextprotocol/servers',
  ],
  [
    'A very long headline written on purpose to check that news cards clamp their titles gracefully on narrow phones and wide desktops alike, without breaking the layout',
    '这是一条刻意写得非常长的新闻标题，用来检查新闻卡片在窄屏手机和宽屏桌面上是否都能优雅地截断标题而不破坏整体布局',
    'https://blog.example.dev/long-headline',
    '',
    '',
  ],
]

/** `Show HN: {name} – {what}` */
export const SHOW_NAMES = [
  'Tessera',
  'Quill',
  'Lantern',
  'Moss',
  'Halyard',
  'Pebble',
  'Kestrel',
  'Inkwell',
  'Marlin',
  'Sundial',
  'Thimble',
  'Juniper',
  'Osprey',
  'Cinder',
]
export const SHOW_WHAT: Array<[string, string]> = [
  ['a local-first RAG for your notes', '给笔记用的本地优先 RAG'],
  ['an MCP server for Postgres', '面向 Postgres 的 MCP 服务器'],
  ['a terminal UI for llama.cpp', 'llama.cpp 的终端界面'],
  ['evals for agents in 50 lines of YAML', '用 50 行 YAML 给智能体写评测'],
  ['a tiny vector database in a single C file', '单个 C 文件实现的迷你向量数据库'],
  ['run open-weights models in the browser with WebGPU', '用 WebGPU 在浏览器里跑开放权重模型'],
  ['an open-source alternative to hosted coding agents', '托管式编程智能体的开源替代品'],
  ['speech-to-speech translation that runs on a phone', '能在手机上运行的语音到语音翻译'],
  ['a prompt debugger with time travel', '支持“时间回溯”的提示词调试器'],
  ['fine-tune a 7B model on a gaming laptop', '在游戏本上微调 7B 模型'],
  ['a sandbox for letting agents use your shell safely', '让智能体安全使用你终端的沙箱'],
  ['structured output for any LLM via grammar-constrained decoding', '用语法约束解码让任意大模型输出结构化结果'],
  ['I taught a robot arm to fold laundry with imitation learning', '我用模仿学习教会了机械臂叠衣服'],
  ['a search engine for arXiv that actually understands equations', '一个真正看得懂公式的 arXiv 搜索引擎'],
]

/** `{org} {action}` */
export const ORG_NAMES: Array<[string, string, string]> = [
  ['OpenAI', 'OpenAI ', 'openai.com'],
  ['Anthropic', 'Anthropic ', 'anthropic.com'],
  ['Google DeepMind', '谷歌 DeepMind ', 'deepmind.google'],
  ['Meta', 'Meta ', 'ai.meta.com'],
  ['Mistral', 'Mistral ', 'mistral.ai'],
  ['The Qwen team', 'Qwen 团队', 'qwenlm.github.io'],
  ['Hugging Face', 'Hugging Face ', 'huggingface.co'],
  ['NVIDIA', '英伟达', 'developer.nvidia.com'],
  ['Apple', '苹果', 'machinelearning.apple.com'],
  ['Moonshot AI', '月之暗面', 'moonshot.ai'],
]
export const ORG_ACTIONS: Array<[string, string]> = [
  ['open-sources its agent evaluation harness', '开源了自家的智能体评测框架'],
  ['ships a one-million-token context window', '上线百万 token 上下文窗口'],
  ['releases a small model for on-device use', '发布面向端侧的小模型'],
  ['publishes a guide to building reliable agents', '发布构建可靠智能体的指南'],
  ['introduces a new open-weights reasoning model', '推出新的开放权重推理模型'],
  ['cuts inference prices for its flagship model', '下调旗舰模型的推理价格'],
  ['details its approach to long-horizon tool use', '详解其长程工具调用的做法'],
  ['releases an open dataset of 10M agent trajectories', '开放 1000 万条智能体轨迹数据集'],
  ['adds native MCP support to its SDK', '在 SDK 中加入原生 MCP 支持'],
  ['announces a speech-native multimodal model', '发布原生语音的多模态模型'],
]

/** Essays and opinion pieces. */
export const ESSAYS: Array<[string, string, string]> = [
  ['LLMs are not compilers', '大模型不是编译器', 'blog.example.dev'],
  ['The bitter lesson, revisited', '重读《苦涩的教训》', 'essays.example.org'],
  ['Notes on building with MCP', '用 MCP 构建应用的一些笔记', 'simonwillison.net'],
  ['I replaced my CI scripts with an agent and regret it', '我用智能体替换了 CI 脚本，现在后悔了', 'blog.example.dev'],
  ['Context engineering is the new prompt engineering', '上下文工程是新的提示词工程', 'essays.example.org'],
  ['How we cut our inference bill by 70%', '我们如何把推理账单砍掉 70%', 'engineering.example.com'],
  ['Evals are all you need', '你只需要评测', 'essays.example.org'],
  ['A field guide to KV-cache tricks', 'KV 缓存技巧实用指南', 'blog.example.dev'],
  ['The case against agent frameworks', '反对智能体框架的理由', 'blog.example.dev'],
  ['Running a 70B model on a used workstation', '在二手工作站上跑 70B 模型', 'blog.example.dev'],
  ['Why small models keep winning on the edge', '为什么小模型在端侧持续胜出', 'essays.example.org'],
  ['What reasoning models still cannot do', '推理模型仍然做不到的事', 'essays.example.org'],
  ['Writing a tokenizer from scratch in Rust', '用 Rust 从零写一个分词器', 'blog.example.dev'],
  ['The hidden cost of tool calls', '工具调用的隐性成本', 'engineering.example.com'],
  ['Vector search is a feature, not a product', '向量搜索是功能，不是产品', 'blog.example.dev'],
  ['Lessons from fine-tuning 200 models', '微调 200 个模型的经验', 'engineering.example.com'],
]

type SignalSeed = [
  key: string,
  weight: number,
  cap: number,
  curve: SignalMeta['curve'],
  en: string,
  zh: string,
  helpEn: string,
  helpZh: string,
]

const SIGNALS: Record<BoardMeta['board'], SignalSeed[]> = {
  repos: [
    [
      'stars_today',
      40,
      1500,
      'log',
      'Stars today',
      '今日新增星标',
      'Stars gained in the last day (trending page, else the delta between our snapshots).',
      '过去一天新增的星标数（取自 Trending 页面，否则为两次快照之差）。',
    ],
    [
      'momentum',
      15,
      30,
      'sqrt',
      'Momentum',
      '增长势头',
      'Stars today as a percentage of all stars: small repos taking off score high.',
      '今日新增星标占总星标的百分比：正在起飞的小项目得分更高。',
    ],
    [
      'hn_echo',
      15,
      500,
      'log',
      'HN echo',
      'HN 回响',
      'Points of Hacker News stories that link to this repo today.',
      '今天链接到该仓库的 Hacker News 帖子的得分之和。',
    ],
    [
      'paper_echo',
      10,
      100,
      'log',
      'Paper echo',
      '论文回响',
      'Upvotes of the paper this repo implements, if it is on the papers board today.',
      '该仓库所实现论文的点赞数（若论文今天也在榜）。',
    ],
    [
      'novelty',
      10,
      1,
      'linear',
      'Novelty',
      '新鲜度',
      '1 on first appearance, decaying the longer it stays on the board.',
      '首次上榜为 1，在榜时间越长衰减越多。',
    ],
    [
      'relevance',
      10,
      1,
      'linear',
      'Relevance',
      '相关度',
      'How squarely the repo is on topic, from keywords and GitHub topics.',
      '根据关键词与 GitHub topics 判断仓库与主题的贴合程度。',
    ],
  ],
  hf: [
    [
      'trending_score',
      50,
      100,
      'log',
      'Trending score',
      '趋势分',
      'Hugging Face official model trending score.',
      'Hugging Face 官方模型热度趋势得分。',
    ],
    [
      'hf_likes',
      30,
      1000,
      'log',
      'Likes',
      '点赞',
      'Total number of likes given by the community.',
      '社区用户给出的总点赞数。',
    ],
    [
      'novelty',
      10,
      1,
      'linear',
      'Novelty',
      '新鲜度',
      'First appearance bonus decaying with the number of earlier editions on the board.',
      '首次上榜的新颖度加成。',
    ],
    [
      'relevance',
      10,
      1,
      'linear',
      'Relevance',
      '主题相关度',
      'Classifier score measuring relevance to core AI topics.',
      '核心人工智能主题相关度得分。',
    ],
  ],
  news: [
    ['points', 40, 800, 'log', 'Points', '得分', 'Hacker News points.', 'Hacker News 得分。'],
    ['comments', 15, 400, 'log', 'Comments', '评论数', 'Number of comments on the story.', '帖子下的评论数量。'],
    [
      'velocity',
      20,
      60,
      'sqrt',
      'Velocity',
      '升温速度',
      'Points per hour since posting (age floored at two hours).',
      '发帖以来每小时获得的分数（帖龄至少按两小时计）。',
    ],
    [
      'echo',
      15,
      2,
      'linear',
      'Echo',
      '跨榜回响',
      'How many other boards this story points into (a repo, a paper, or both).',
      '该帖子指向了几个其他榜单（仓库、论文，或两者）。',
    ],
    [
      'relevance',
      10,
      1,
      'linear',
      'Relevance',
      '相关度',
      'How squarely the story is on topic.',
      '帖子与主题的贴合程度。',
    ],
  ],
  social: [
    [
      'lift',
      30,
      5,
      'sqrt',
      'Lift',
      '超常表现',
      'How far the post beats its usual audience; via names the baseline: the author’s median (X), the community’s usual score (Reddit), or — when Reddit is read over RSS, which has no votes — the post’s position in its community’s Top-Today list.',
      '帖子比平常的受众表现好多少；via 说明基准：作者的中位数（X）、社区的常见得分（Reddit），或在通过 RSS 读取 Reddit（没有投票数）时，帖子在该社区“今日热门”中的位置。',
    ],
    [
      'reach',
      20,
      5000,
      'log',
      'Reach',
      '传播量',
      'X: likes + 2 × reposts + 3 × quotes + replies. Reddit: score (0 in RSS mode).',
      'X：点赞 + 2 × 转发 + 3 × 引用 + 回复。Reddit：得分（RSS 模式下为 0）。',
    ],
    [
      'discussion',
      10,
      500,
      'log',
      'Discussion',
      '讨论度',
      'Replies (X) or comments (Reddit).',
      '回复数（X）或评论数（Reddit）。',
    ],
    [
      'velocity',
      10,
      500,
      'sqrt',
      'Velocity',
      '升温速度',
      'Reach per hour since posting (age floored at half an hour).',
      '发帖以来每小时的传播量（帖龄至少按半小时计）。',
    ],
    [
      'authority',
      15,
      1.5,
      'linear',
      'Authority',
      '来源权重',
      'Watch-list weight of the account or community in config.yaml.',
      'config.yaml 中该账号或社区的关注权重。',
    ],
    [
      'echo',
      10,
      2,
      'linear',
      'Echo',
      '跨榜回响',
      'Other boards the post links into or is linked from today.',
      '今天与该帖子互相链接的其他榜单数量。',
    ],
    [
      'relevance',
      5,
      1,
      'linear',
      'Relevance',
      '主题相关度',
      'How squarely the post is on topic.',
      '帖子与主题的贴合程度。',
    ],
  ],
  labs: [
    [
      'kind',
      25,
      1,
      'linear',
      'Kind',
      '类型',
      'Model 1 · product 0.7 · research 0.6 · engineering 0.5 · company 0.35.',
      '模型 1 · 产品 0.7 · 研究 0.6 · 工程 0.5 · 公司 0.35。',
    ],
    [
      'release',
      10,
      0.7,
      'linear',
      'Release',
      '发布加成',
      '+0.5 for a model release, +0.2 more for a flagship name.',
      '模型发布加 0.5，旗舰型号再加 0.2。',
    ],
    [
      'freshness',
      30,
      1,
      'linear',
      'Freshness',
      '新鲜度',
      '0.5^(age in hours / 24): 1 at publication, halving every day of the 7-day look-back.',
      '0.5^(发布小时数 / 24)：刚发布为 1，在 7 天回看期内每天减半。',
    ],
    [
      'echo',
      20,
      1.5,
      'linear',
      'Echo',
      '外部关注',
      'Hacker News, Reddit and X attention on posts linking to it.',
      '链接到该动态的 Hacker News、Reddit 与 X 帖子获得的关注。',
    ],
    [
      'company',
      10,
      1.5,
      'linear',
      'Company',
      '公司权重',
      'The company’s weight in config.yaml.',
      'config.yaml 中该公司的权重。',
    ],
    [
      'surface',
      5,
      0.2,
      'linear',
      'Surface',
      '发布渠道',
      'Blog 0.2 · changelog 0.1 · GitHub or Hugging Face 0.',
      '博客 0.2 · 更新日志 0.1 · GitHub 或 Hugging Face 0。',
    ],
  ],
}

const BOARD_TEXT: Record<BoardMeta['board'], [string, string, string, string]> = {
  repos: ['Repos', '开源项目', 'What builders are starring on GitHub', '开发者正在 GitHub 上点星的项目'],
  hf: ['HF Trending', 'HF 趋势', 'Trending models on Hugging Face', 'Hugging Face 上的热门模型'],
  news: ['Hacker News', 'Hacker News 热议', 'What hackers are arguing about', '极客们正在争论的话题'],
  social: [
    'Social',
    '社区热议',
    'What labs, people and AI communities are saying',
    '实验室、业内人士与 AI 社区在聊什么',
  ],
  labs: ['Labs', '官方动态', 'What AI companies officially shipped', 'AI 公司官方发布了什么'],
}

/** Board + signal metadata as the pipeline would publish it (mirrors the weights in `config.yaml`). */
export function boardMeta(): BoardMeta[] {
  return BOARDS.map((board) => {
    const [en, zh, subEn, subZh] = BOARD_TEXT[board]
    const meta: BoardMeta = {
      board,
      title: { en, zh },
      subtitle: { en: subEn, zh: subZh },
      size: 10,
      runnersUp: 10,
      signals: SIGNALS[board].map(([key, weight, cap, curve, labelEn, labelZh, helpEn, helpZh]) => ({
        key,
        weight,
        cap,
        curve,
        label: { en: labelEn, zh: labelZh },
        help: { en: helpEn, zh: helpZh },
      })),
    }
    if (board === 'labs') meta.lookbackDays = 7
    return meta
  })
}

/** Filler paper title endings, `[en, zh]`, so the title pool comfortably covers 45 editions. */
export const PAPER_SUFFIX: Array<[string, string]> = [
  ['', ''],
  [': A Benchmark', '：一个基准'],
  [' at Scale', '（规模化研究）'],
  [' with Verifiable Rewards', '：基于可验证奖励'],
  [': Limits and Remedies', '：局限与对策'],
  [' without Labels', '：无需标注'],
]

/** Fictional Reddit usernames. */
export const REDDITORS = [
  'tensor_tinkerer',
  'quantized_quokka',
  'gradient_gardener',
  'attn_is_all',
  'moe_money',
  'kv_cache_me',
  'lora_explorer',
  'sparse_sam',
  'batchnorm_betty',
  'token_whisperer',
  'vram_hoarder',
  'epoch_eater',
]

/** Generic top-comment texts for Reddit threads (no author names are stored, as in the pipeline). */
export const COMMENTS = [
  'Ran it locally last night; the long-context claims hold up to about 400K tokens for me.',
  'The licence is the real news here.',
  'Benchmarks look great, but I want to see independent evals before switching.',
  'Tried it on our internal eval set: six points over the previous version.',
  'Does the quantised version keep tool calling intact? That is the part that usually breaks.',
  'First release where the small model is actually usable for agents.',
  'Pricing is aggressive — everyone else will have to respond.',
  'Docs are thin, but the example repo is excellent.',
]
